//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: controlplane/v1/common.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus_Code int32

const (
	ResponseStatus_CODE_UNSPECIFIED      ResponseStatus_Code = 0
	ResponseStatus_CODE_OK               ResponseStatus_Code = 1
	ResponseStatus_CODE_ERROR            ResponseStatus_Code = 2
	ResponseStatus_CODE_NOT_FOUND        ResponseStatus_Code = 3
	ResponseStatus_CODE_INVALID_ARGUMENT ResponseStatus_Code = 4
	ResponseStatus_CODE_UNAVAILABLE      ResponseStatus_Code = 5
)

// Enum value maps for ResponseStatus_Code.
var (
	ResponseStatus_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_OK",
		2: "CODE_ERROR",
		3: "CODE_NOT_FOUND",
		4: "CODE_INVALID_ARGUMENT",
		5: "CODE_UNAVAILABLE",
	}
	ResponseStatus_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":      0,
		"CODE_OK":               1,
		"CODE_ERROR":            2,
		"CODE_NOT_FOUND":        3,
		"CODE_INVALID_ARGUMENT": 4,
		"CODE_UNAVAILABLE":      5,
	}
)

func (x ResponseStatus_Code) Enum() *ResponseStatus_Code {
	p := new(ResponseStatus_Code)
	*p = x
	return p
}

func (x ResponseStatus_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_common_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus_Code) Type() protoreflect.EnumType {
	return &file_controlplane_v1_common_proto_enumTypes[0]
}

func (x ResponseStatus_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus_Code.Descriptor instead.
func (ResponseStatus_Code) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_common_proto_rawDescGZIP(), []int{2, 0}
}

// Agent 身份标识
type AgentIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent 唯一标识: ${hostname}-${pid}-${startTimeMillis}
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 主机名
	HostName string `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	// 进程 ID
	ProcessId string `protobuf:"bytes,3,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// SDK 版本
	SdkVersion string `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// 服务名称
	ServiceName string `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// 服务命名空间
	ServiceNamespace string `protobuf:"bytes,6,opt,name=service_namespace,json=serviceNamespace,proto3" json:"service_namespace,omitempty"`
	// Agent 启动时间 (毫秒时间戳)
	StartTimeMillis int64 `protobuf:"varint,7,opt,name=start_time_millis,json=startTimeMillis,proto3" json:"start_time_millis,omitempty"`
	// 扩展属性
	Attributes    map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIdentity) Reset() {
	*x = AgentIdentity{}
	mi := &file_controlplane_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIdentity) ProtoMessage() {}

func (x *AgentIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIdentity.ProtoReflect.Descriptor instead.
func (*AgentIdentity) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *AgentIdentity) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentIdentity) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AgentIdentity) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *AgentIdentity) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *AgentIdentity) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AgentIdentity) GetServiceNamespace() string {
	if x != nil {
		return x.ServiceNamespace
	}
	return ""
}

func (x *AgentIdentity) GetStartTimeMillis() int64 {
	if x != nil {
		return x.StartTimeMillis
	}
	return 0
}

func (x *AgentIdentity) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// 配置版本信息
type ConfigVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置版本号
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// 配置时间戳 (毫秒时间戳)
	TimestampMillis int64 `protobuf:"varint,2,opt,name=timestamp_millis,json=timestampMillis,proto3" json:"timestamp_millis,omitempty"`
	// ETag (用于 HTTP 缓存)
	Etag          string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVersion) Reset() {
	*x = ConfigVersion{}
	mi := &file_controlplane_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersion) ProtoMessage() {}

func (x *ConfigVersion) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersion.ProtoReflect.Descriptor instead.
func (*ConfigVersion) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigVersion) GetTimestampMillis() int64 {
	if x != nil {
		return x.TimestampMillis
	}
	return 0
}

func (x *ConfigVersion) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// 通用响应状态
type ResponseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseStatus_Code    `protobuf:"varint,1,opt,name=code,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus_Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_controlplane_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseStatus) GetCode() ResponseStatus_Code {
	if x != nil {
		return x.Code
	}
	return ResponseStatus_CODE_UNSPECIFIED
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_controlplane_v1_common_proto protoreflect.FileDescriptor

const file_controlplane_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1ccontrolplane/v1/common.proto\x120io.opentelemetry.extension.controlplane.proto.v1\"\xb3\x03\n" +
	"\rAgentIdentity\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12\x1d\n" +
	"\n" +
	"process_id\x18\x03 \x01(\tR\tprocessId\x12\x1f\n" +
	"\vsdk_version\x18\x04 \x01(\tR\n" +
	"sdkVersion\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12+\n" +
	"\x11service_namespace\x18\x06 \x01(\tR\x10serviceNamespace\x12*\n" +
	"\x11start_time_millis\x18\a \x01(\x03R\x0fstartTimeMillis\x12o\n" +
	"\n" +
	"attributes\x18\b \x03(\v2O.io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\rConfigVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10timestamp_millis\x18\x02 \x01(\x03R\x0ftimestampMillis\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\"\x85\x02\n" +
	"\x0eResponseStatus\x12Y\n" +
	"\x04code\x18\x01 \x01(\x0e2E.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"~\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCODE_OK\x10\x01\x12\x0e\n" +
	"\n" +
	"CODE_ERROR\x10\x02\x12\x12\n" +
	"\x0eCODE_NOT_FOUND\x10\x03\x12\x19\n" +
	"\x15CODE_INVALID_ARGUMENT\x10\x04\x12\x14\n" +
	"\x10CODE_UNAVAILABLE\x10\x05B\x8f\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\fCommonProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_common_proto_rawDescOnce sync.Once
	file_controlplane_v1_common_proto_rawDescData []byte
)

func file_controlplane_v1_common_proto_rawDescGZIP() []byte {
	file_controlplane_v1_common_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_common_proto_rawDesc), len(file_controlplane_v1_common_proto_rawDesc)))
	})
	return file_controlplane_v1_common_proto_rawDescData
}

var file_controlplane_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_controlplane_v1_common_proto_goTypes = []any{
	(ResponseStatus_Code)(0), // 0: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus.Code
	(*AgentIdentity)(nil),    // 1: io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	(*ConfigVersion)(nil),    // 2: io.opentelemetry.extension.controlplane.proto.v1.ConfigVersion
	(*ResponseStatus)(nil),   // 3: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	nil,                      // 4: io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity.AttributesEntry
}
var file_controlplane_v1_common_proto_depIdxs = []int32{
	4, // 0: io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity.attributes:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity.AttributesEntry
	0, // 1: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus.code:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus.Code
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_controlplane_v1_common_proto_init() }
func file_controlplane_v1_common_proto_init() {
	if File_controlplane_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_common_proto_rawDesc), len(file_controlplane_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_common_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_common_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_common_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_common_proto_msgTypes,
	}.Build()
	File_controlplane_v1_common_proto = out.File
	file_controlplane_v1_common_proto_goTypes = nil
	file_controlplane_v1_common_proto_depIdxs = nil
}
