//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: controlplane/v1/config.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 采样器类型
type SamplerConfig_SamplerType int32

const (
	SamplerConfig_SAMPLER_TYPE_UNSPECIFIED    SamplerConfig_SamplerType = 0
	SamplerConfig_SAMPLER_TYPE_ALWAYS_ON      SamplerConfig_SamplerType = 1
	SamplerConfig_SAMPLER_TYPE_ALWAYS_OFF     SamplerConfig_SamplerType = 2
	SamplerConfig_SAMPLER_TYPE_TRACE_ID_RATIO SamplerConfig_SamplerType = 3
	SamplerConfig_SAMPLER_TYPE_PARENT_BASED   SamplerConfig_SamplerType = 4
	SamplerConfig_SAMPLER_TYPE_RULE_BASED     SamplerConfig_SamplerType = 5
)

// Enum value maps for SamplerConfig_SamplerType.
var (
	SamplerConfig_SamplerType_name = map[int32]string{
		0: "SAMPLER_TYPE_UNSPECIFIED",
		1: "SAMPLER_TYPE_ALWAYS_ON",
		2: "SAMPLER_TYPE_ALWAYS_OFF",
		3: "SAMPLER_TYPE_TRACE_ID_RATIO",
		4: "SAMPLER_TYPE_PARENT_BASED",
		5: "SAMPLER_TYPE_RULE_BASED",
	}
	SamplerConfig_SamplerType_value = map[string]int32{
		"SAMPLER_TYPE_UNSPECIFIED":    0,
		"SAMPLER_TYPE_ALWAYS_ON":      1,
		"SAMPLER_TYPE_ALWAYS_OFF":     2,
		"SAMPLER_TYPE_TRACE_ID_RATIO": 3,
		"SAMPLER_TYPE_PARENT_BASED":   4,
		"SAMPLER_TYPE_RULE_BASED":     5,
	}
)

func (x SamplerConfig_SamplerType) Enum() *SamplerConfig_SamplerType {
	p := new(SamplerConfig_SamplerType)
	*p = x
	return p
}

func (x SamplerConfig_SamplerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SamplerConfig_SamplerType) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_config_proto_enumTypes[0].Descriptor()
}

func (SamplerConfig_SamplerType) Type() protoreflect.EnumType {
	return &file_controlplane_v1_config_proto_enumTypes[0]
}

func (x SamplerConfig_SamplerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SamplerConfig_SamplerType.Descriptor instead.
func (SamplerConfig_SamplerType) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{3, 0}
}

// 确认状态
type ConfigAcknowledgement_Status int32

const (
	ConfigAcknowledgement_STATUS_UNSPECIFIED ConfigAcknowledgement_Status = 0
	ConfigAcknowledgement_STATUS_APPLIED     ConfigAcknowledgement_Status = 1 // 完全生效
	ConfigAcknowledgement_STATUS_PARTIAL     ConfigAcknowledgement_Status = 2 // 部分生效
	ConfigAcknowledgement_STATUS_FAILED      ConfigAcknowledgement_Status = 3 // 应用失败
)

// Enum value maps for ConfigAcknowledgement_Status.
var (
	ConfigAcknowledgement_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_APPLIED",
		2: "STATUS_PARTIAL",
		3: "STATUS_FAILED",
	}
	ConfigAcknowledgement_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_APPLIED":     1,
		"STATUS_PARTIAL":     2,
		"STATUS_FAILED":      3,
	}
)

func (x ConfigAcknowledgement_Status) Enum() *ConfigAcknowledgement_Status {
	p := new(ConfigAcknowledgement_Status)
	*p = x
	return p
}

func (x ConfigAcknowledgement_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigAcknowledgement_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_config_proto_enumTypes[1].Descriptor()
}

func (ConfigAcknowledgement_Status) Type() protoreflect.EnumType {
	return &file_controlplane_v1_config_proto_enumTypes[1]
}

func (x ConfigAcknowledgement_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigAcknowledgement_Status.Descriptor instead.
func (ConfigAcknowledgement_Status) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{6, 0}
}

// 配置拉取请求
type ConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent 身份标识
	AgentIdentity *AgentIdentity `protobuf:"bytes,1,opt,name=agent_identity,json=agentIdentity,proto3" json:"agent_identity,omitempty"`
	// Agent ID 字符串（与 DTO 兼容，优先使用此字段）
	AgentId string `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 当前配置版本 (首次请求为空)
	CurrentVersion *ConfigVersion `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	// 当前配置版本字符串（与 DTO 兼容）
	CurrentConfigVersion string `protobuf:"bytes,6,opt,name=current_config_version,json=currentConfigVersion,proto3" json:"current_config_version,omitempty"`
	// 当前配置 ETag（与 DTO 兼容）
	CurrentEtag string `protobuf:"bytes,7,opt,name=current_etag,json=currentEtag,proto3" json:"current_etag,omitempty"`
	// 长轮询超时时间 (毫秒)
	LongPollTimeoutMillis int64 `protobuf:"varint,3,opt,name=long_poll_timeout_millis,json=longPollTimeoutMillis,proto3" json:"long_poll_timeout_millis,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_controlplane_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigRequest) GetAgentIdentity() *AgentIdentity {
	if x != nil {
		return x.AgentIdentity
	}
	return nil
}

func (x *ConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConfigRequest) GetCurrentVersion() *ConfigVersion {
	if x != nil {
		return x.CurrentVersion
	}
	return nil
}

func (x *ConfigRequest) GetCurrentConfigVersion() string {
	if x != nil {
		return x.CurrentConfigVersion
	}
	return ""
}

func (x *ConfigRequest) GetCurrentEtag() string {
	if x != nil {
		return x.CurrentEtag
	}
	return ""
}

func (x *ConfigRequest) GetLongPollTimeoutMillis() int64 {
	if x != nil {
		return x.LongPollTimeoutMillis
	}
	return 0
}

// 配置拉取响应
type ConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 配置内容 (如果有变更)
	Config *AgentConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// 是否有配置变更
	HasChanges bool `protobuf:"varint,3,opt,name=has_changes,json=hasChanges,proto3" json:"has_changes,omitempty"`
	// 下次轮询建议间隔 (毫秒)
	SuggestedPollIntervalMillis int64 `protobuf:"varint,4,opt,name=suggested_poll_interval_millis,json=suggestedPollIntervalMillis,proto3" json:"suggested_poll_interval_millis,omitempty"`
	// 配置版本字符串（与 DTO 兼容）
	ConfigVersion string `protobuf:"bytes,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// 配置 ETag（与 DTO 兼容）
	Etag string `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	// 是否成功（与 DTO 兼容）
	Success bool `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（与 DTO 兼容）
	ErrorMessage  string `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_controlplane_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ConfigResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigResponse) GetHasChanges() bool {
	if x != nil {
		return x.HasChanges
	}
	return false
}

func (x *ConfigResponse) GetSuggestedPollIntervalMillis() int64 {
	if x != nil {
		return x.SuggestedPollIntervalMillis
	}
	return 0
}

func (x *ConfigResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConfigResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Agent 配置 (所有字段均支持热更新)
type AgentConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置版本
	Version *ConfigVersion `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// 采样配置
	Sampler *SamplerConfig `protobuf:"bytes,2,opt,name=sampler,proto3" json:"sampler,omitempty"`
	// 批处理配置
	Batch *BatchConfig `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	// 动态资源属性
	DynamicResourceAttributes map[string]string `protobuf:"bytes,4,rep,name=dynamic_resource_attributes,json=dynamicResourceAttributes,proto3" json:"dynamic_resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 扩展配置 (JSON 格式)
	ExtensionConfigJson string `protobuf:"bytes,5,opt,name=extension_config_json,json=extensionConfigJson,proto3" json:"extension_config_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_controlplane_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfig) GetVersion() *ConfigVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *AgentConfig) GetSampler() *SamplerConfig {
	if x != nil {
		return x.Sampler
	}
	return nil
}

func (x *AgentConfig) GetBatch() *BatchConfig {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *AgentConfig) GetDynamicResourceAttributes() map[string]string {
	if x != nil {
		return x.DynamicResourceAttributes
	}
	return nil
}

func (x *AgentConfig) GetExtensionConfigJson() string {
	if x != nil {
		return x.ExtensionConfigJson
	}
	return ""
}

// 采样配置
type SamplerConfig struct {
	state protoimpl.MessageState    `protogen:"open.v1"`
	Type  SamplerConfig_SamplerType `protobuf:"varint,1,opt,name=type,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig_SamplerType" json:"type,omitempty"`
	// 采样率 (0.0 ~ 1.0)
	Ratio float64 `protobuf:"fixed64,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
	// 采样规则
	Rules         []*SamplerRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplerConfig) Reset() {
	*x = SamplerConfig{}
	mi := &file_controlplane_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplerConfig) ProtoMessage() {}

func (x *SamplerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplerConfig.ProtoReflect.Descriptor instead.
func (*SamplerConfig) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *SamplerConfig) GetType() SamplerConfig_SamplerType {
	if x != nil {
		return x.Type
	}
	return SamplerConfig_SAMPLER_TYPE_UNSPECIFIED
}

func (x *SamplerConfig) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *SamplerConfig) GetRules() []*SamplerRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// 采样规则
type SamplerRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 规则名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Span 名称匹配模式 (正则表达式)
	SpanNamePattern string `protobuf:"bytes,2,opt,name=span_name_pattern,json=spanNamePattern,proto3" json:"span_name_pattern,omitempty"`
	// 属性匹配条件
	AttributeMatch map[string]string `protobuf:"bytes,3,rep,name=attribute_match,json=attributeMatch,proto3" json:"attribute_match,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 命中规则的采样率
	Ratio float64 `protobuf:"fixed64,4,opt,name=ratio,proto3" json:"ratio,omitempty"`
	// 规则优先级 (数值越大优先级越高)
	Priority      int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplerRule) Reset() {
	*x = SamplerRule{}
	mi := &file_controlplane_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplerRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplerRule) ProtoMessage() {}

func (x *SamplerRule) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplerRule.ProtoReflect.Descriptor instead.
func (*SamplerRule) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *SamplerRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SamplerRule) GetSpanNamePattern() string {
	if x != nil {
		return x.SpanNamePattern
	}
	return ""
}

func (x *SamplerRule) GetAttributeMatch() map[string]string {
	if x != nil {
		return x.AttributeMatch
	}
	return nil
}

func (x *SamplerRule) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *SamplerRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// 批处理配置
type BatchConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 批处理大小
	MaxExportBatchSize int32 `protobuf:"varint,1,opt,name=max_export_batch_size,json=maxExportBatchSize,proto3" json:"max_export_batch_size,omitempty"`
	// 队列大小
	MaxQueueSize int32 `protobuf:"varint,2,opt,name=max_queue_size,json=maxQueueSize,proto3" json:"max_queue_size,omitempty"`
	// 调度延迟 (毫秒)
	ScheduleDelayMillis int64 `protobuf:"varint,3,opt,name=schedule_delay_millis,json=scheduleDelayMillis,proto3" json:"schedule_delay_millis,omitempty"`
	// 导出超时 (毫秒)
	ExportTimeoutMillis int64 `protobuf:"varint,4,opt,name=export_timeout_millis,json=exportTimeoutMillis,proto3" json:"export_timeout_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchConfig) Reset() {
	*x = BatchConfig{}
	mi := &file_controlplane_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchConfig) ProtoMessage() {}

func (x *BatchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchConfig.ProtoReflect.Descriptor instead.
func (*BatchConfig) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *BatchConfig) GetMaxExportBatchSize() int32 {
	if x != nil {
		return x.MaxExportBatchSize
	}
	return 0
}

func (x *BatchConfig) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *BatchConfig) GetScheduleDelayMillis() int64 {
	if x != nil {
		return x.ScheduleDelayMillis
	}
	return 0
}

func (x *BatchConfig) GetExportTimeoutMillis() int64 {
	if x != nil {
		return x.ExportTimeoutMillis
	}
	return 0
}

// 配置确认请求 (通过状态上报实现)
type ConfigAcknowledgement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置版本
	ConfigVersion string                       `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Status        ConfigAcknowledgement_Status `protobuf:"varint,2,opt,name=status,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement_Status" json:"status,omitempty"`
	// 已生效的配置字段
	AppliedFields []string `protobuf:"bytes,3,rep,name=applied_fields,json=appliedFields,proto3" json:"applied_fields,omitempty"`
	// 失败的配置字段
	FailedFields []string `protobuf:"bytes,4,rep,name=failed_fields,json=failedFields,proto3" json:"failed_fields,omitempty"`
	// 错误信息
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAcknowledgement) Reset() {
	*x = ConfigAcknowledgement{}
	mi := &file_controlplane_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAcknowledgement) ProtoMessage() {}

func (x *ConfigAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAcknowledgement.ProtoReflect.Descriptor instead.
func (*ConfigAcknowledgement) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigAcknowledgement) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConfigAcknowledgement) GetStatus() ConfigAcknowledgement_Status {
	if x != nil {
		return x.Status
	}
	return ConfigAcknowledgement_STATUS_UNSPECIFIED
}

func (x *ConfigAcknowledgement) GetAppliedFields() []string {
	if x != nil {
		return x.AppliedFields
	}
	return nil
}

func (x *ConfigAcknowledgement) GetFailedFields() []string {
	if x != nil {
		return x.FailedFields
	}
	return nil
}

func (x *ConfigAcknowledgement) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_controlplane_v1_config_proto protoreflect.FileDescriptor

const file_controlplane_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1ccontrolplane/v1/config.proto\x120io.opentelemetry.extension.controlplane.proto.v1\x1a\x1ccontrolplane/v1/common.proto\"\x8e\x03\n" +
	"\rConfigRequest\x12f\n" +
	"\x0eagent_identity\x18\x01 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.AgentIdentityR\ragentIdentity\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12h\n" +
	"\x0fcurrent_version\x18\x02 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.ConfigVersionR\x0ecurrentVersion\x124\n" +
	"\x16current_config_version\x18\x06 \x01(\tR\x14currentConfigVersion\x12!\n" +
	"\fcurrent_etag\x18\a \x01(\tR\vcurrentEtag\x127\n" +
	"\x18long_poll_timeout_millis\x18\x03 \x01(\x03R\x15longPollTimeoutMillis\"\xa1\x03\n" +
	"\x0eConfigResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12U\n" +
	"\x06config\x18\x02 \x01(\v2=.io.opentelemetry.extension.controlplane.proto.v1.AgentConfigR\x06config\x12\x1f\n" +
	"\vhas_changes\x18\x03 \x01(\bR\n" +
	"hasChanges\x12C\n" +
	"\x1esuggested_poll_interval_millis\x18\x04 \x01(\x03R\x1bsuggestedPollIntervalMillis\x12%\n" +
	"\x0econfig_version\x18\x05 \x01(\tR\rconfigVersion\x12\x12\n" +
	"\x04etag\x18\x06 \x01(\tR\x04etag\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\xb9\x04\n" +
	"\vAgentConfig\x12Y\n" +
	"\aversion\x18\x01 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.ConfigVersionR\aversion\x12Y\n" +
	"\asampler\x18\x02 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.SamplerConfigR\asampler\x12S\n" +
	"\x05batch\x18\x03 \x01(\v2=.io.opentelemetry.extension.controlplane.proto.v1.BatchConfigR\x05batch\x12\x9c\x01\n" +
	"\x1bdynamic_resource_attributes\x18\x04 \x03(\v2\\.io.opentelemetry.extension.controlplane.proto.v1.AgentConfig.DynamicResourceAttributesEntryR\x19dynamicResourceAttributes\x122\n" +
	"\x15extension_config_json\x18\x05 \x01(\tR\x13extensionConfigJson\x1aL\n" +
	"\x1eDynamicResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x03\n" +
	"\rSamplerConfig\x12_\n" +
	"\x04type\x18\x01 \x01(\x0e2K.io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig.SamplerTypeR\x04type\x12\x14\n" +
	"\x05ratio\x18\x02 \x01(\x01R\x05ratio\x12S\n" +
	"\x05rules\x18\x03 \x03(\v2=.io.opentelemetry.extension.controlplane.proto.v1.SamplerRuleR\x05rules\"\xc1\x01\n" +
	"\vSamplerType\x12\x1c\n" +
	"\x18SAMPLER_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SAMPLER_TYPE_ALWAYS_ON\x10\x01\x12\x1b\n" +
	"\x17SAMPLER_TYPE_ALWAYS_OFF\x10\x02\x12\x1f\n" +
	"\x1bSAMPLER_TYPE_TRACE_ID_RATIO\x10\x03\x12\x1d\n" +
	"\x19SAMPLER_TYPE_PARENT_BASED\x10\x04\x12\x1b\n" +
	"\x17SAMPLER_TYPE_RULE_BASED\x10\x05\"\xbe\x02\n" +
	"\vSamplerRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x11span_name_pattern\x18\x02 \x01(\tR\x0fspanNamePattern\x12z\n" +
	"\x0fattribute_match\x18\x03 \x03(\v2Q.io.opentelemetry.extension.controlplane.proto.v1.SamplerRule.AttributeMatchEntryR\x0eattributeMatch\x12\x14\n" +
	"\x05ratio\x18\x04 \x01(\x01R\x05ratio\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x1aA\n" +
	"\x13AttributeMatchEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\vBatchConfig\x121\n" +
	"\x15max_export_batch_size\x18\x01 \x01(\x05R\x12maxExportBatchSize\x12$\n" +
	"\x0emax_queue_size\x18\x02 \x01(\x05R\fmaxQueueSize\x122\n" +
	"\x15schedule_delay_millis\x18\x03 \x01(\x03R\x13scheduleDelayMillis\x122\n" +
	"\x15export_timeout_millis\x18\x04 \x01(\x03R\x13exportTimeoutMillis\"\xf4\x02\n" +
	"\x15ConfigAcknowledgement\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12f\n" +
	"\x06status\x18\x02 \x01(\x0e2N.io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement.StatusR\x06status\x12%\n" +
	"\x0eapplied_fields\x18\x03 \x03(\tR\rappliedFields\x12#\n" +
	"\rfailed_fields\x18\x04 \x03(\tR\ffailedFields\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"[\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_APPLIED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PARTIAL\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03B\x8f\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\fConfigProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_config_proto_rawDescOnce sync.Once
	file_controlplane_v1_config_proto_rawDescData []byte
)

func file_controlplane_v1_config_proto_rawDescGZIP() []byte {
	file_controlplane_v1_config_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_config_proto_rawDesc), len(file_controlplane_v1_config_proto_rawDesc)))
	})
	return file_controlplane_v1_config_proto_rawDescData
}

var file_controlplane_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_controlplane_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_controlplane_v1_config_proto_goTypes = []any{
	(SamplerConfig_SamplerType)(0),    // 0: io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig.SamplerType
	(ConfigAcknowledgement_Status)(0), // 1: io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement.Status
	(*ConfigRequest)(nil),             // 2: io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest
	(*ConfigResponse)(nil),            // 3: io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse
	(*AgentConfig)(nil),               // 4: io.opentelemetry.extension.controlplane.proto.v1.AgentConfig
	(*SamplerConfig)(nil),             // 5: io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig
	(*SamplerRule)(nil),               // 6: io.opentelemetry.extension.controlplane.proto.v1.SamplerRule
	(*BatchConfig)(nil),               // 7: io.opentelemetry.extension.controlplane.proto.v1.BatchConfig
	(*ConfigAcknowledgement)(nil),     // 8: io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement
	nil,                               // 9: io.opentelemetry.extension.controlplane.proto.v1.AgentConfig.DynamicResourceAttributesEntry
	nil,                               // 10: io.opentelemetry.extension.controlplane.proto.v1.SamplerRule.AttributeMatchEntry
	(*AgentIdentity)(nil),             // 11: io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	(*ConfigVersion)(nil),             // 12: io.opentelemetry.extension.controlplane.proto.v1.ConfigVersion
	(*ResponseStatus)(nil),            // 13: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
}
var file_controlplane_v1_config_proto_depIdxs = []int32{
	11, // 0: io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest.agent_identity:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	12, // 1: io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest.current_version:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ConfigVersion
	13, // 2: io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	4,  // 3: io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse.config:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentConfig
	12, // 4: io.opentelemetry.extension.controlplane.proto.v1.AgentConfig.version:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ConfigVersion
	5,  // 5: io.opentelemetry.extension.controlplane.proto.v1.AgentConfig.sampler:type_name -> io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig
	7,  // 6: io.opentelemetry.extension.controlplane.proto.v1.AgentConfig.batch:type_name -> io.opentelemetry.extension.controlplane.proto.v1.BatchConfig
	9,  // 7: io.opentelemetry.extension.controlplane.proto.v1.AgentConfig.dynamic_resource_attributes:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentConfig.DynamicResourceAttributesEntry
	0,  // 8: io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig.type:type_name -> io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig.SamplerType
	6,  // 9: io.opentelemetry.extension.controlplane.proto.v1.SamplerConfig.rules:type_name -> io.opentelemetry.extension.controlplane.proto.v1.SamplerRule
	10, // 10: io.opentelemetry.extension.controlplane.proto.v1.SamplerRule.attribute_match:type_name -> io.opentelemetry.extension.controlplane.proto.v1.SamplerRule.AttributeMatchEntry
	1,  // 11: io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement.Status
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_controlplane_v1_config_proto_init() }
func file_controlplane_v1_config_proto_init() {
	if File_controlplane_v1_config_proto != nil {
		return
	}
	file_controlplane_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_config_proto_rawDesc), len(file_controlplane_v1_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_config_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_config_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_config_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_config_proto_msgTypes,
	}.Build()
	File_controlplane_v1_config_proto = out.File
	file_controlplane_v1_config_proto_goTypes = nil
	file_controlplane_v1_config_proto_depIdxs = nil
}
