//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: controlplane/v1/poll.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务结果状态（稳定集合）
type TaskResultStatus int32

const (
	// 未指定
	TaskResultStatus_TASK_RESULT_STATUS_UNSPECIFIED TaskResultStatus = 0
	// 任务待执行
	TaskResultStatus_TASK_RESULT_STATUS_PENDING TaskResultStatus = 1
	// 任务执行中
	TaskResultStatus_TASK_RESULT_STATUS_RUNNING TaskResultStatus = 2
	// 任务执行成功
	TaskResultStatus_TASK_RESULT_STATUS_SUCCESS TaskResultStatus = 3
	// 任务执行失败（包括过期、过旧、被拒绝等，具体原因见 error_code）
	TaskResultStatus_TASK_RESULT_STATUS_FAILED TaskResultStatus = 4
	// 任务执行超时
	TaskResultStatus_TASK_RESULT_STATUS_TIMEOUT TaskResultStatus = 5
	// 任务被取消
	TaskResultStatus_TASK_RESULT_STATUS_CANCELLED TaskResultStatus = 6
)

// Enum value maps for TaskResultStatus.
var (
	TaskResultStatus_name = map[int32]string{
		0: "TASK_RESULT_STATUS_UNSPECIFIED",
		1: "TASK_RESULT_STATUS_PENDING",
		2: "TASK_RESULT_STATUS_RUNNING",
		3: "TASK_RESULT_STATUS_SUCCESS",
		4: "TASK_RESULT_STATUS_FAILED",
		5: "TASK_RESULT_STATUS_TIMEOUT",
		6: "TASK_RESULT_STATUS_CANCELLED",
	}
	TaskResultStatus_value = map[string]int32{
		"TASK_RESULT_STATUS_UNSPECIFIED": 0,
		"TASK_RESULT_STATUS_PENDING":     1,
		"TASK_RESULT_STATUS_RUNNING":     2,
		"TASK_RESULT_STATUS_SUCCESS":     3,
		"TASK_RESULT_STATUS_FAILED":      4,
		"TASK_RESULT_STATUS_TIMEOUT":     5,
		"TASK_RESULT_STATUS_CANCELLED":   6,
	}
)

func (x TaskResultStatus) Enum() *TaskResultStatus {
	p := new(TaskResultStatus)
	*p = x
	return p
}

func (x TaskResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_poll_proto_enumTypes[0].Descriptor()
}

func (TaskResultStatus) Type() protoreflect.EnumType {
	return &file_controlplane_v1_poll_proto_enumTypes[0]
}

func (x TaskResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResultStatus.Descriptor instead.
func (TaskResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{0}
}

// 统一轮询请求
// 同时获取配置更新和待执行任务，减少 HTTP 往返
type UnifiedPollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent 身份标识
	AgentIdentity *AgentIdentity `protobuf:"bytes,1,opt,name=agent_identity,json=agentIdentity,proto3" json:"agent_identity,omitempty"`
	// Agent ID 字符串（与 DTO 兼容，优先使用此字段）
	AgentId string `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 当前配置版本信息
	CurrentConfigVersion *ConfigVersion `protobuf:"bytes,2,opt,name=current_config_version,json=currentConfigVersion,proto3" json:"current_config_version,omitempty"`
	// 当前配置版本字符串（与 DTO 兼容）
	CurrentConfigVersionStr string `protobuf:"bytes,7,opt,name=current_config_version_str,json=currentConfigVersionStr,proto3" json:"current_config_version_str,omitempty"`
	// 当前配置 ETag（与 DTO 兼容）
	CurrentConfigEtag string `protobuf:"bytes,8,opt,name=current_config_etag,json=currentConfigEtag,proto3" json:"current_config_etag,omitempty"`
	// 长轮询超时时间 (毫秒)
	TimeoutMillis int64 `protobuf:"varint,3,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	// Agent 当前能力（用于任务下发筛选）
	Capabilities  *AgentCapabilities `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedPollRequest) Reset() {
	*x = UnifiedPollRequest{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedPollRequest) ProtoMessage() {}

func (x *UnifiedPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedPollRequest.ProtoReflect.Descriptor instead.
func (*UnifiedPollRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{0}
}

func (x *UnifiedPollRequest) GetAgentIdentity() *AgentIdentity {
	if x != nil {
		return x.AgentIdentity
	}
	return nil
}

func (x *UnifiedPollRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnifiedPollRequest) GetCurrentConfigVersion() *ConfigVersion {
	if x != nil {
		return x.CurrentConfigVersion
	}
	return nil
}

func (x *UnifiedPollRequest) GetCurrentConfigVersionStr() string {
	if x != nil {
		return x.CurrentConfigVersionStr
	}
	return ""
}

func (x *UnifiedPollRequest) GetCurrentConfigEtag() string {
	if x != nil {
		return x.CurrentConfigEtag
	}
	return ""
}

func (x *UnifiedPollRequest) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *UnifiedPollRequest) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// 统一轮询响应
type UnifiedPollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 是否有任何变更（配置或任务）
	HasAnyChanges bool `protobuf:"varint,2,opt,name=has_any_changes,json=hasAnyChanges,proto3" json:"has_any_changes,omitempty"`
	// 各类型轮询结果，key 为 "CONFIG" 或 "TASK"
	Results map[string]*PollResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 下次轮询建议间隔 (毫秒)
	SuggestedPollIntervalMillis int64 `protobuf:"varint,4,opt,name=suggested_poll_interval_millis,json=suggestedPollIntervalMillis,proto3" json:"suggested_poll_interval_millis,omitempty"`
	// 是否成功（与 DTO 兼容）
	Success bool `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（与 DTO 兼容）
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedPollResponse) Reset() {
	*x = UnifiedPollResponse{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedPollResponse) ProtoMessage() {}

func (x *UnifiedPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedPollResponse.ProtoReflect.Descriptor instead.
func (*UnifiedPollResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{1}
}

func (x *UnifiedPollResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UnifiedPollResponse) GetHasAnyChanges() bool {
	if x != nil {
		return x.HasAnyChanges
	}
	return false
}

func (x *UnifiedPollResponse) GetResults() map[string]*PollResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *UnifiedPollResponse) GetSuggestedPollIntervalMillis() int64 {
	if x != nil {
		return x.SuggestedPollIntervalMillis
	}
	return 0
}

func (x *UnifiedPollResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnifiedPollResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 单类型轮询结果
type PollResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 结果类型: "CONFIG" 或 "TASK"
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// 是否有变更
	HasChanges bool `protobuf:"varint,2,opt,name=has_changes,json=hasChanges,proto3" json:"has_changes,omitempty"`
	// 配置数据
	ConfigData []byte `protobuf:"bytes,3,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	// 配置版本
	ConfigVersion string `protobuf:"bytes,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// 配置 ETag
	ConfigEtag string `protobuf:"bytes,5,opt,name=config_etag,json=configEtag,proto3" json:"config_etag,omitempty"`
	// 下发的任务列表
	Tasks []*Task `protobuf:"bytes,6,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// 额外信息
	Message       string `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResult) Reset() {
	*x = PollResult{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResult) ProtoMessage() {}

func (x *PollResult) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResult.ProtoReflect.Descriptor instead.
func (*PollResult) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{2}
}

func (x *PollResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PollResult) GetHasChanges() bool {
	if x != nil {
		return x.HasChanges
	}
	return false
}

func (x *PollResult) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *PollResult) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *PollResult) GetConfigEtag() string {
	if x != nil {
		return x.ConfigEtag
	}
	return ""
}

func (x *PollResult) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *PollResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 任务结果上报请求
type TaskResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务 ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Agent 身份标识
	AgentIdentity *AgentIdentity `protobuf:"bytes,2,opt,name=agent_identity,json=agentIdentity,proto3" json:"agent_identity,omitempty"`
	// Agent ID 字符串（与 DTO 兼容，优先使用此字段）
	AgentId string `protobuf:"bytes,10,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 任务执行状态
	Status TaskResultStatus `protobuf:"varint,3,opt,name=status,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.TaskResultStatus" json:"status,omitempty"`
	// 错误码（失败时），如 TASK_STALE、TASK_EXPIRED、TASK_REJECTED
	ErrorCode string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 错误信息（失败时）
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 任务输出结果（成功时，JSON 格式）
	ResultData []byte `protobuf:"bytes,6,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	// 任务输出结果 JSON 格式（与 DTO 兼容）
	ResultJson string `protobuf:"bytes,11,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// 任务开始执行时间 (毫秒时间戳)
	StartedAtMillis int64 `protobuf:"varint,7,opt,name=started_at_millis,json=startedAtMillis,proto3" json:"started_at_millis,omitempty"`
	// 任务完成时间 (毫秒时间戳)
	CompletedAtMillis int64 `protobuf:"varint,8,opt,name=completed_at_millis,json=completedAtMillis,proto3" json:"completed_at_millis,omitempty"`
	// 任务执行耗时 (毫秒)
	ExecutionTimeMillis int64 `protobuf:"varint,9,opt,name=execution_time_millis,json=executionTimeMillis,proto3" json:"execution_time_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultRequest) GetAgentIdentity() *AgentIdentity {
	if x != nil {
		return x.AgentIdentity
	}
	return nil
}

func (x *TaskResultRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskResultRequest) GetStatus() TaskResultStatus {
	if x != nil {
		return x.Status
	}
	return TaskResultStatus_TASK_RESULT_STATUS_UNSPECIFIED
}

func (x *TaskResultRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TaskResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResultRequest) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *TaskResultRequest) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *TaskResultRequest) GetStartedAtMillis() int64 {
	if x != nil {
		return x.StartedAtMillis
	}
	return 0
}

func (x *TaskResultRequest) GetCompletedAtMillis() int64 {
	if x != nil {
		return x.CompletedAtMillis
	}
	return 0
}

func (x *TaskResultRequest) GetExecutionTimeMillis() int64 {
	if x != nil {
		return x.ExecutionTimeMillis
	}
	return 0
}

// 任务结果上报响应
type TaskResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 是否成功接收
	Acknowledged bool `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// 是否成功（与 DTO 兼容）
	Success bool `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（与 DTO 兼容）
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 额外信息
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultResponse) Reset() {
	*x = TaskResultResponse{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultResponse) ProtoMessage() {}

func (x *TaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultResponse.ProtoReflect.Descriptor instead.
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResultResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TaskResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *TaskResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_controlplane_v1_poll_proto protoreflect.FileDescriptor

const file_controlplane_v1_poll_proto_rawDesc = "" +
	"\n" +
	"\x1acontrolplane/v1/poll.proto\x120io.opentelemetry.extension.controlplane.proto.v1\x1a\x1ccontrolplane/v1/common.proto\x1a\x1ccontrolplane/v1/config.proto\x1a\x1acontrolplane/v1/task.proto\"\x8b\x04\n" +
	"\x12UnifiedPollRequest\x12f\n" +
	"\x0eagent_identity\x18\x01 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.AgentIdentityR\ragentIdentity\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12u\n" +
	"\x16current_config_version\x18\x02 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.ConfigVersionR\x14currentConfigVersion\x12;\n" +
	"\x1acurrent_config_version_str\x18\a \x01(\tR\x17currentConfigVersionStr\x12.\n" +
	"\x13current_config_etag\x18\b \x01(\tR\x11currentConfigEtag\x12%\n" +
	"\x0etimeout_millis\x18\x03 \x01(\x03R\rtimeoutMillis\x12g\n" +
	"\fcapabilities\x18\x04 \x01(\v2C.io.opentelemetry.extension.controlplane.proto.v1.AgentCapabilitiesR\fcapabilities\"\x83\x04\n" +
	"\x13UnifiedPollResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12&\n" +
	"\x0fhas_any_changes\x18\x02 \x01(\bR\rhasAnyChanges\x12l\n" +
	"\aresults\x18\x03 \x03(\v2R.io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.ResultsEntryR\aresults\x12C\n" +
	"\x1esuggested_poll_interval_millis\x18\x04 \x01(\x03R\x1bsuggestedPollIntervalMillis\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x1ax\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12R\n" +
	"\x05value\x18\x02 \x01(\v2<.io.opentelemetry.extension.controlplane.proto.v1.PollResultR\x05value:\x028\x01\"\x92\x02\n" +
	"\n" +
	"PollResult\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vhas_changes\x18\x02 \x01(\bR\n" +
	"hasChanges\x12\x1f\n" +
	"\vconfig_data\x18\x03 \x01(\fR\n" +
	"configData\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\tR\rconfigVersion\x12\x1f\n" +
	"\vconfig_etag\x18\x05 \x01(\tR\n" +
	"configEtag\x12L\n" +
	"\x05tasks\x18\x06 \x03(\v26.io.opentelemetry.extension.controlplane.proto.v1.TaskR\x05tasks\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xa1\x04\n" +
	"\x11TaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12f\n" +
	"\x0eagent_identity\x18\x02 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.AgentIdentityR\ragentIdentity\x12\x19\n" +
	"\bagent_id\x18\n" +
	" \x01(\tR\aagentId\x12Z\n" +
	"\x06status\x18\x03 \x01(\x0e2B.io.opentelemetry.extension.controlplane.proto.v1.TaskResultStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vresult_data\x18\x06 \x01(\fR\n" +
	"resultData\x12\x1f\n" +
	"\vresult_json\x18\v \x01(\tR\n" +
	"resultJson\x12*\n" +
	"\x11started_at_millis\x18\a \x01(\x03R\x0fstartedAtMillis\x12.\n" +
	"\x13completed_at_millis\x18\b \x01(\x03R\x11completedAtMillis\x122\n" +
	"\x15execution_time_millis\x18\t \x01(\x03R\x13executionTimeMillis\"\xeb\x01\n" +
	"\x12TaskResultResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\xf7\x01\n" +
	"\x10TaskResultStatus\x12\"\n" +
	"\x1eTASK_RESULT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTASK_RESULT_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aTASK_RESULT_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aTASK_RESULT_STATUS_SUCCESS\x10\x03\x12\x1d\n" +
	"\x19TASK_RESULT_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aTASK_RESULT_STATUS_TIMEOUT\x10\x05\x12 \n" +
	"\x1cTASK_RESULT_STATUS_CANCELLED\x10\x06B\x8d\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\n" +
	"PollProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_poll_proto_rawDescOnce sync.Once
	file_controlplane_v1_poll_proto_rawDescData []byte
)

func file_controlplane_v1_poll_proto_rawDescGZIP() []byte {
	file_controlplane_v1_poll_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_poll_proto_rawDesc), len(file_controlplane_v1_poll_proto_rawDesc)))
	})
	return file_controlplane_v1_poll_proto_rawDescData
}

var file_controlplane_v1_poll_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_v1_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_controlplane_v1_poll_proto_goTypes = []any{
	(TaskResultStatus)(0),       // 0: io.opentelemetry.extension.controlplane.proto.v1.TaskResultStatus
	(*UnifiedPollRequest)(nil),  // 1: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest
	(*UnifiedPollResponse)(nil), // 2: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse
	(*PollResult)(nil),          // 3: io.opentelemetry.extension.controlplane.proto.v1.PollResult
	(*TaskResultRequest)(nil),   // 4: io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest
	(*TaskResultResponse)(nil),  // 5: io.opentelemetry.extension.controlplane.proto.v1.TaskResultResponse
	nil,                         // 6: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.ResultsEntry
	(*AgentIdentity)(nil),       // 7: io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	(*ConfigVersion)(nil),       // 8: io.opentelemetry.extension.controlplane.proto.v1.ConfigVersion
	(*AgentCapabilities)(nil),   // 9: io.opentelemetry.extension.controlplane.proto.v1.AgentCapabilities
	(*ResponseStatus)(nil),      // 10: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	(*Task)(nil),                // 11: io.opentelemetry.extension.controlplane.proto.v1.Task
}
var file_controlplane_v1_poll_proto_depIdxs = []int32{
	7,  // 0: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest.agent_identity:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	8,  // 1: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest.current_config_version:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ConfigVersion
	9,  // 2: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest.capabilities:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentCapabilities
	10, // 3: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	6,  // 4: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.results:type_name -> io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.ResultsEntry
	11, // 5: io.opentelemetry.extension.controlplane.proto.v1.PollResult.tasks:type_name -> io.opentelemetry.extension.controlplane.proto.v1.Task
	7,  // 6: io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest.agent_identity:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	0,  // 7: io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.TaskResultStatus
	10, // 8: io.opentelemetry.extension.controlplane.proto.v1.TaskResultResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	3,  // 9: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.ResultsEntry.value:type_name -> io.opentelemetry.extension.controlplane.proto.v1.PollResult
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_controlplane_v1_poll_proto_init() }
func file_controlplane_v1_poll_proto_init() {
	if File_controlplane_v1_poll_proto != nil {
		return
	}
	file_controlplane_v1_common_proto_init()
	file_controlplane_v1_config_proto_init()
	file_controlplane_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_poll_proto_rawDesc), len(file_controlplane_v1_poll_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_poll_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_poll_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_poll_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_poll_proto_msgTypes,
	}.Build()
	File_controlplane_v1_poll_proto = out.File
	file_controlplane_v1_poll_proto_goTypes = nil
	file_controlplane_v1_poll_proto_depIdxs = nil
}
