//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: controlplane/v1/poll.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一轮询请求
// 同时获取配置更新和待执行任务，减少 HTTP 往返
// 直接复用 ConfigRequest 和 TaskRequest，避免字段漂移
type UnifiedPollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID 字符串（用于鉴权和路由，优先级高于子请求中的 agent_id）
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 长轮询超时时间 (毫秒，优先级高于子请求中的 timeout)
	TimeoutMillis int64 `protobuf:"varint,2,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	// 配置请求（复用 config.proto）
	ConfigRequest *ConfigRequest `protobuf:"bytes,3,opt,name=config_request,json=configRequest,proto3" json:"config_request,omitempty"`
	// 任务请求（复用 task.proto）
	TaskRequest   *TaskRequest `protobuf:"bytes,4,opt,name=task_request,json=taskRequest,proto3" json:"task_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedPollRequest) Reset() {
	*x = UnifiedPollRequest{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedPollRequest) ProtoMessage() {}

func (x *UnifiedPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedPollRequest.ProtoReflect.Descriptor instead.
func (*UnifiedPollRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{0}
}

func (x *UnifiedPollRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnifiedPollRequest) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *UnifiedPollRequest) GetConfigRequest() *ConfigRequest {
	if x != nil {
		return x.ConfigRequest
	}
	return nil
}

func (x *UnifiedPollRequest) GetTaskRequest() *TaskRequest {
	if x != nil {
		return x.TaskRequest
	}
	return nil
}

// 统一轮询响应
// 直接复用 ConfigResponse 和 TaskResponse，避免字段漂移
type UnifiedPollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 是否有任何变更（配置或任务）
	HasAnyChanges bool `protobuf:"varint,2,opt,name=has_any_changes,json=hasAnyChanges,proto3" json:"has_any_changes,omitempty"`
	// 配置响应（复用 config.proto）
	ConfigResponse *ConfigResponse `protobuf:"bytes,3,opt,name=config_response,json=configResponse,proto3" json:"config_response,omitempty"`
	// 任务响应（复用 task.proto）
	TaskResponse *TaskResponse `protobuf:"bytes,4,opt,name=task_response,json=taskResponse,proto3" json:"task_response,omitempty"`
	// 下次轮询建议间隔 (毫秒)
	SuggestedPollIntervalMillis int64 `protobuf:"varint,5,opt,name=suggested_poll_interval_millis,json=suggestedPollIntervalMillis,proto3" json:"suggested_poll_interval_millis,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UnifiedPollResponse) Reset() {
	*x = UnifiedPollResponse{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedPollResponse) ProtoMessage() {}

func (x *UnifiedPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedPollResponse.ProtoReflect.Descriptor instead.
func (*UnifiedPollResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{1}
}

func (x *UnifiedPollResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UnifiedPollResponse) GetHasAnyChanges() bool {
	if x != nil {
		return x.HasAnyChanges
	}
	return false
}

func (x *UnifiedPollResponse) GetConfigResponse() *ConfigResponse {
	if x != nil {
		return x.ConfigResponse
	}
	return nil
}

func (x *UnifiedPollResponse) GetTaskResponse() *TaskResponse {
	if x != nil {
		return x.TaskResponse
	}
	return nil
}

func (x *UnifiedPollResponse) GetSuggestedPollIntervalMillis() int64 {
	if x != nil {
		return x.SuggestedPollIntervalMillis
	}
	return 0
}

// 任务结果上报请求
// 直接复用 TaskResult (task.proto)，避免字段漂移
type TaskResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID 字符串（用于鉴权和路由）
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 任务结果（复用 task.proto 的 TaskResult）
	Result        *TaskResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResultRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskResultRequest) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 任务结果上报响应
type TaskResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 是否成功接收
	Acknowledged bool `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// 额外信息
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultResponse) Reset() {
	*x = TaskResultResponse{}
	mi := &file_controlplane_v1_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultResponse) ProtoMessage() {}

func (x *TaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultResponse.ProtoReflect.Descriptor instead.
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_poll_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResultResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TaskResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *TaskResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_controlplane_v1_poll_proto protoreflect.FileDescriptor

const file_controlplane_v1_poll_proto_rawDesc = "" +
	"\n" +
	"\x1acontrolplane/v1/poll.proto\x120io.opentelemetry.extension.controlplane.proto.v1\x1a\x1ccontrolplane/v1/common.proto\x1a\x1ccontrolplane/v1/config.proto\x1a\x1acontrolplane/v1/task.proto\"\xa0\x02\n" +
	"\x12UnifiedPollRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12%\n" +
	"\x0etimeout_millis\x18\x02 \x01(\x03R\rtimeoutMillis\x12f\n" +
	"\x0econfig_request\x18\x03 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.ConfigRequestR\rconfigRequest\x12`\n" +
	"\ftask_request\x18\x04 \x01(\v2=.io.opentelemetry.extension.controlplane.proto.v1.TaskRequestR\vtaskRequest\"\xac\x03\n" +
	"\x13UnifiedPollResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12&\n" +
	"\x0fhas_any_changes\x18\x02 \x01(\bR\rhasAnyChanges\x12i\n" +
	"\x0fconfig_response\x18\x03 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ConfigResponseR\x0econfigResponse\x12c\n" +
	"\rtask_response\x18\x04 \x01(\v2>.io.opentelemetry.extension.controlplane.proto.v1.TaskResponseR\ftaskResponse\x12C\n" +
	"\x1esuggested_poll_interval_millis\x18\x05 \x01(\x03R\x1bsuggestedPollIntervalMillis\"\x84\x01\n" +
	"\x11TaskResultRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12T\n" +
	"\x06result\x18\x02 \x01(\v2<.io.opentelemetry.extension.controlplane.proto.v1.TaskResultR\x06result\"\xac\x01\n" +
	"\x12TaskResultResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\x8d\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\n" +
	"PollProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_poll_proto_rawDescOnce sync.Once
	file_controlplane_v1_poll_proto_rawDescData []byte
)

func file_controlplane_v1_poll_proto_rawDescGZIP() []byte {
	file_controlplane_v1_poll_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_poll_proto_rawDesc), len(file_controlplane_v1_poll_proto_rawDesc)))
	})
	return file_controlplane_v1_poll_proto_rawDescData
}

var file_controlplane_v1_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_controlplane_v1_poll_proto_goTypes = []any{
	(*UnifiedPollRequest)(nil),  // 0: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest
	(*UnifiedPollResponse)(nil), // 1: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse
	(*TaskResultRequest)(nil),   // 2: io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest
	(*TaskResultResponse)(nil),  // 3: io.opentelemetry.extension.controlplane.proto.v1.TaskResultResponse
	(*ConfigRequest)(nil),       // 4: io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest
	(*TaskRequest)(nil),         // 5: io.opentelemetry.extension.controlplane.proto.v1.TaskRequest
	(*ResponseStatus)(nil),      // 6: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	(*ConfigResponse)(nil),      // 7: io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse
	(*TaskResponse)(nil),        // 8: io.opentelemetry.extension.controlplane.proto.v1.TaskResponse
	(*TaskResult)(nil),          // 9: io.opentelemetry.extension.controlplane.proto.v1.TaskResult
}
var file_controlplane_v1_poll_proto_depIdxs = []int32{
	4, // 0: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest.config_request:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest
	5, // 1: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest.task_request:type_name -> io.opentelemetry.extension.controlplane.proto.v1.TaskRequest
	6, // 2: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	7, // 3: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.config_response:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse
	8, // 4: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse.task_response:type_name -> io.opentelemetry.extension.controlplane.proto.v1.TaskResponse
	9, // 5: io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest.result:type_name -> io.opentelemetry.extension.controlplane.proto.v1.TaskResult
	6, // 6: io.opentelemetry.extension.controlplane.proto.v1.TaskResultResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_controlplane_v1_poll_proto_init() }
func file_controlplane_v1_poll_proto_init() {
	if File_controlplane_v1_poll_proto != nil {
		return
	}
	file_controlplane_v1_common_proto_init()
	file_controlplane_v1_config_proto_init()
	file_controlplane_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_poll_proto_rawDesc), len(file_controlplane_v1_poll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_poll_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_poll_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_poll_proto_msgTypes,
	}.Build()
	File_controlplane_v1_poll_proto = out.File
	file_controlplane_v1_poll_proto_goTypes = nil
	file_controlplane_v1_poll_proto_depIdxs = nil
}
