//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: controlplane/v1/service.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_UnifiedPoll_FullMethodName         = "/io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService/UnifiedPoll"
	ControlPlaneService_ReportTaskResult_FullMethodName    = "/io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService/ReportTaskResult"
	ControlPlaneService_GetConfig_FullMethodName           = "/io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService/GetConfig"
	ControlPlaneService_GetTasks_FullMethodName            = "/io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService/GetTasks"
	ControlPlaneService_ReportStatus_FullMethodName        = "/io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService/ReportStatus"
	ControlPlaneService_UploadChunkedResult_FullMethodName = "/io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService/UploadChunkedResult"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 控制平面服务 (一元长轮询模式，预留双向流扩展)
type ControlPlaneServiceClient interface {
	// 统一长轮询（同时获取配置和任务）
	// 这是推荐的主要方法，一次请求同时获取配置更新和待执行任务
	UnifiedPoll(ctx context.Context, in *UnifiedPollRequest, opts ...grpc.CallOption) (*UnifiedPollResponse, error)
	// 上报任务执行结果
	ReportTaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error)
	// 获取配置 (长轮询)
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// 获取任务 (长轮询)
	GetTasks(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// 上报状态
	ReportStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 上传分片结果
	UploadChunkedResult(ctx context.Context, in *ChunkedTaskResult, opts ...grpc.CallOption) (*ChunkedUploadResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) UnifiedPoll(ctx context.Context, in *UnifiedPollRequest, opts ...grpc.CallOption) (*UnifiedPollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnifiedPollResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UnifiedPoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReportTaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetTasks(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReportStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UploadChunkedResult(ctx context.Context, in *ChunkedTaskResult, opts ...grpc.CallOption) (*ChunkedUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkedUploadResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UploadChunkedResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// 控制平面服务 (一元长轮询模式，预留双向流扩展)
type ControlPlaneServiceServer interface {
	// 统一长轮询（同时获取配置和任务）
	// 这是推荐的主要方法，一次请求同时获取配置更新和待执行任务
	UnifiedPoll(context.Context, *UnifiedPollRequest) (*UnifiedPollResponse, error)
	// 上报任务执行结果
	ReportTaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error)
	// 获取配置 (长轮询)
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	// 获取任务 (长轮询)
	GetTasks(context.Context, *TaskRequest) (*TaskResponse, error)
	// 上报状态
	ReportStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	// 上传分片结果
	UploadChunkedResult(context.Context, *ChunkedTaskResult) (*ChunkedUploadResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) UnifiedPoll(context.Context, *UnifiedPollRequest) (*UnifiedPollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnifiedPoll not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReportTaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetTasks(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReportStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedControlPlaneServiceServer) UploadChunkedResult(context.Context, *ChunkedTaskResult) (*ChunkedUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadChunkedResult not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_UnifiedPoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnifiedPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UnifiedPoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UnifiedPoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UnifiedPoll(ctx, req.(*UnifiedPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReportTaskResult(ctx, req.(*TaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetTasks(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReportStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UploadChunkedResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkedTaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UploadChunkedResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UploadChunkedResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UploadChunkedResult(ctx, req.(*ChunkedTaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnifiedPoll",
			Handler:    _ControlPlaneService_UnifiedPoll_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _ControlPlaneService_ReportTaskResult_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ControlPlaneService_GetConfig_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _ControlPlaneService_GetTasks_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _ControlPlaneService_ReportStatus_Handler,
		},
		{
			MethodName: "UploadChunkedResult",
			Handler:    _ControlPlaneService_UploadChunkedResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane/v1/service.proto",
}
