//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: controlplane/v1/service.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_controlplane_v1_service_proto protoreflect.FileDescriptor

const file_controlplane_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dcontrolplane/v1/service.proto\x120io.opentelemetry.extension.controlplane.proto.v1\x1a\x1ccontrolplane/v1/config.proto\x1a\x1acontrolplane/v1/task.proto\x1a\x1ccontrolplane/v1/status.proto\x1a\x1acontrolplane/v1/poll.proto2\xa9\a\n" +
	"\x13ControlPlaneService\x12\x9a\x01\n" +
	"\vUnifiedPoll\x12D.io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest\x1aE.io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse\x12\x9d\x01\n" +
	"\x10ReportTaskResult\x12C.io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest\x1aD.io.opentelemetry.extension.controlplane.proto.v1.TaskResultResponse\x12\x8e\x01\n" +
	"\tGetConfig\x12?.io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest\x1a@.io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse\x12\x89\x01\n" +
	"\bGetTasks\x12=.io.opentelemetry.extension.controlplane.proto.v1.TaskRequest\x1a>.io.opentelemetry.extension.controlplane.proto.v1.TaskResponse\x12\x91\x01\n" +
	"\fReportStatus\x12?.io.opentelemetry.extension.controlplane.proto.v1.StatusRequest\x1a@.io.opentelemetry.extension.controlplane.proto.v1.StatusResponse\x12\xa3\x01\n" +
	"\x13UploadChunkedResult\x12C.io.opentelemetry.extension.controlplane.proto.v1.ChunkedTaskResult\x1aG.io.opentelemetry.extension.controlplane.proto.v1.ChunkedUploadResponseB\x90\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\rServiceProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var file_controlplane_v1_service_proto_goTypes = []any{
	(*UnifiedPollRequest)(nil),    // 0: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest
	(*TaskResultRequest)(nil),     // 1: io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest
	(*ConfigRequest)(nil),         // 2: io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest
	(*TaskRequest)(nil),           // 3: io.opentelemetry.extension.controlplane.proto.v1.TaskRequest
	(*StatusRequest)(nil),         // 4: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest
	(*ChunkedTaskResult)(nil),     // 5: io.opentelemetry.extension.controlplane.proto.v1.ChunkedTaskResult
	(*UnifiedPollResponse)(nil),   // 6: io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse
	(*TaskResultResponse)(nil),    // 7: io.opentelemetry.extension.controlplane.proto.v1.TaskResultResponse
	(*ConfigResponse)(nil),        // 8: io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse
	(*TaskResponse)(nil),          // 9: io.opentelemetry.extension.controlplane.proto.v1.TaskResponse
	(*StatusResponse)(nil),        // 10: io.opentelemetry.extension.controlplane.proto.v1.StatusResponse
	(*ChunkedUploadResponse)(nil), // 11: io.opentelemetry.extension.controlplane.proto.v1.ChunkedUploadResponse
}
var file_controlplane_v1_service_proto_depIdxs = []int32{
	0,  // 0: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.UnifiedPoll:input_type -> io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollRequest
	1,  // 1: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.ReportTaskResult:input_type -> io.opentelemetry.extension.controlplane.proto.v1.TaskResultRequest
	2,  // 2: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.GetConfig:input_type -> io.opentelemetry.extension.controlplane.proto.v1.ConfigRequest
	3,  // 3: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.GetTasks:input_type -> io.opentelemetry.extension.controlplane.proto.v1.TaskRequest
	4,  // 4: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.ReportStatus:input_type -> io.opentelemetry.extension.controlplane.proto.v1.StatusRequest
	5,  // 5: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.UploadChunkedResult:input_type -> io.opentelemetry.extension.controlplane.proto.v1.ChunkedTaskResult
	6,  // 6: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.UnifiedPoll:output_type -> io.opentelemetry.extension.controlplane.proto.v1.UnifiedPollResponse
	7,  // 7: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.ReportTaskResult:output_type -> io.opentelemetry.extension.controlplane.proto.v1.TaskResultResponse
	8,  // 8: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.GetConfig:output_type -> io.opentelemetry.extension.controlplane.proto.v1.ConfigResponse
	9,  // 9: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.GetTasks:output_type -> io.opentelemetry.extension.controlplane.proto.v1.TaskResponse
	10, // 10: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.ReportStatus:output_type -> io.opentelemetry.extension.controlplane.proto.v1.StatusResponse
	11, // 11: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneService.UploadChunkedResult:output_type -> io.opentelemetry.extension.controlplane.proto.v1.ChunkedUploadResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_controlplane_v1_service_proto_init() }
func file_controlplane_v1_service_proto_init() {
	if File_controlplane_v1_service_proto != nil {
		return
	}
	file_controlplane_v1_config_proto_init()
	file_controlplane_v1_task_proto_init()
	file_controlplane_v1_status_proto_init()
	file_controlplane_v1_poll_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_service_proto_rawDesc), len(file_controlplane_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_v1_service_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_service_proto_depIdxs,
	}.Build()
	File_controlplane_v1_service_proto = out.File
	file_controlplane_v1_service_proto_goTypes = nil
	file_controlplane_v1_service_proto_depIdxs = nil
}
