//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: controlplane/v1/status.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状态上报请求（纯心跳）
// 任务结果请使用专用接口 ReportTaskResult 上报
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent 身份标识（完整信息）
	AgentIdentity *AgentIdentity `protobuf:"bytes,1,opt,name=agent_identity,json=agentIdentity,proto3" json:"agent_identity,omitempty"`
	// Agent ID 字符串（简化字段，优先使用）
	// 当只需要 ID 时使用此字段，避免构造完整的 AgentIdentity
	AgentId string `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 上报时间 (毫秒时间戳)
	TimestampMillis int64 `protobuf:"varint,6,opt,name=timestamp_millis,json=timestampMillis,proto3" json:"timestamp_millis,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_controlplane_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetAgentIdentity() *AgentIdentity {
	if x != nil {
		return x.AgentIdentity
	}
	return nil
}

func (x *StatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusRequest) GetTimestampMillis() int64 {
	if x != nil {
		return x.TimestampMillis
	}
	return 0
}

// 状态上报响应
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 服务端时间 (毫秒时间戳)
	ServerTimeMillis int64 `protobuf:"varint,2,opt,name=server_time_millis,json=serverTimeMillis,proto3" json:"server_time_millis,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_controlplane_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusResponse) GetServerTimeMillis() int64 {
	if x != nil {
		return x.ServerTimeMillis
	}
	return 0
}

var File_controlplane_v1_status_proto protoreflect.FileDescriptor

const file_controlplane_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x1ccontrolplane/v1/status.proto\x120io.opentelemetry.extension.controlplane.proto.v1\x1a\x1ccontrolplane/v1/common.proto\"\x9d\x02\n" +
	"\rStatusRequest\x12f\n" +
	"\x0eagent_identity\x18\x01 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.AgentIdentityR\ragentIdentity\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12)\n" +
	"\x10timestamp_millis\x18\x06 \x01(\x03R\x0ftimestampMillisJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\b\x10\tR\fagent_statusR\vjvm_metricsR\ftask_resultsR\n" +
	"config_ackR\vstatus_data\"\x81\x02\n" +
	"\x0eStatusResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12,\n" +
	"\x12server_time_millis\x18\x02 \x01(\x03R\x10serverTimeMillisJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aR suggested_report_interval_millisR\x15acknowledged_task_idsR\asuccessR\rerror_messageB\x8f\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\fStatusProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_status_proto_rawDescOnce sync.Once
	file_controlplane_v1_status_proto_rawDescData []byte
)

func file_controlplane_v1_status_proto_rawDescGZIP() []byte {
	file_controlplane_v1_status_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_status_proto_rawDesc), len(file_controlplane_v1_status_proto_rawDesc)))
	})
	return file_controlplane_v1_status_proto_rawDescData
}

var file_controlplane_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_controlplane_v1_status_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest
	(*StatusResponse)(nil), // 1: io.opentelemetry.extension.controlplane.proto.v1.StatusResponse
	(*AgentIdentity)(nil),  // 2: io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	(*ResponseStatus)(nil), // 3: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
}
var file_controlplane_v1_status_proto_depIdxs = []int32{
	2, // 0: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest.agent_identity:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	3, // 1: io.opentelemetry.extension.controlplane.proto.v1.StatusResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_controlplane_v1_status_proto_init() }
func file_controlplane_v1_status_proto_init() {
	if File_controlplane_v1_status_proto != nil {
		return
	}
	file_controlplane_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_status_proto_rawDesc), len(file_controlplane_v1_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_status_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_status_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_status_proto_msgTypes,
	}.Build()
	File_controlplane_v1_status_proto = out.File
	file_controlplane_v1_status_proto_goTypes = nil
	file_controlplane_v1_status_proto_depIdxs = nil
}
