//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: controlplane/v1/status.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运行状态
type AgentStatus_RunningState int32

const (
	AgentStatus_RUNNING_STATE_UNSPECIFIED AgentStatus_RunningState = 0
	AgentStatus_RUNNING_STATE_STARTING    AgentStatus_RunningState = 1
	AgentStatus_RUNNING_STATE_RUNNING     AgentStatus_RunningState = 2
	AgentStatus_RUNNING_STATE_STOPPING    AgentStatus_RunningState = 3
	AgentStatus_RUNNING_STATE_STOPPED     AgentStatus_RunningState = 4
)

// Enum value maps for AgentStatus_RunningState.
var (
	AgentStatus_RunningState_name = map[int32]string{
		0: "RUNNING_STATE_UNSPECIFIED",
		1: "RUNNING_STATE_STARTING",
		2: "RUNNING_STATE_RUNNING",
		3: "RUNNING_STATE_STOPPING",
		4: "RUNNING_STATE_STOPPED",
	}
	AgentStatus_RunningState_value = map[string]int32{
		"RUNNING_STATE_UNSPECIFIED": 0,
		"RUNNING_STATE_STARTING":    1,
		"RUNNING_STATE_RUNNING":     2,
		"RUNNING_STATE_STOPPING":    3,
		"RUNNING_STATE_STOPPED":     4,
	}
)

func (x AgentStatus_RunningState) Enum() *AgentStatus_RunningState {
	p := new(AgentStatus_RunningState)
	*p = x
	return p
}

func (x AgentStatus_RunningState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus_RunningState) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_status_proto_enumTypes[0].Descriptor()
}

func (AgentStatus_RunningState) Type() protoreflect.EnumType {
	return &file_controlplane_v1_status_proto_enumTypes[0]
}

func (x AgentStatus_RunningState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus_RunningState.Descriptor instead.
func (AgentStatus_RunningState) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{2, 0}
}

// 健康状态
type OtlpExportStatus_HealthState int32

const (
	OtlpExportStatus_HEALTH_STATE_UNSPECIFIED OtlpExportStatus_HealthState = 0
	OtlpExportStatus_HEALTH_STATE_UNKNOWN     OtlpExportStatus_HealthState = 1
	OtlpExportStatus_HEALTH_STATE_HEALTHY     OtlpExportStatus_HealthState = 2
	OtlpExportStatus_HEALTH_STATE_DEGRADED    OtlpExportStatus_HealthState = 3
	OtlpExportStatus_HEALTH_STATE_UNHEALTHY   OtlpExportStatus_HealthState = 4
)

// Enum value maps for OtlpExportStatus_HealthState.
var (
	OtlpExportStatus_HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_UNKNOWN",
		2: "HEALTH_STATE_HEALTHY",
		3: "HEALTH_STATE_DEGRADED",
		4: "HEALTH_STATE_UNHEALTHY",
	}
	OtlpExportStatus_HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_UNKNOWN":     1,
		"HEALTH_STATE_HEALTHY":     2,
		"HEALTH_STATE_DEGRADED":    3,
		"HEALTH_STATE_UNHEALTHY":   4,
	}
)

func (x OtlpExportStatus_HealthState) Enum() *OtlpExportStatus_HealthState {
	p := new(OtlpExportStatus_HealthState)
	*p = x
	return p
}

func (x OtlpExportStatus_HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtlpExportStatus_HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_status_proto_enumTypes[1].Descriptor()
}

func (OtlpExportStatus_HealthState) Type() protoreflect.EnumType {
	return &file_controlplane_v1_status_proto_enumTypes[1]
}

func (x OtlpExportStatus_HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtlpExportStatus_HealthState.Descriptor instead.
func (OtlpExportStatus_HealthState) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{3, 0}
}

// 连接状态
type ControlPlaneStatus_ConnectionState int32

const (
	ControlPlaneStatus_CONNECTION_STATE_UNSPECIFIED      ControlPlaneStatus_ConnectionState = 0
	ControlPlaneStatus_CONNECTION_STATE_CONNECTED        ControlPlaneStatus_ConnectionState = 1
	ControlPlaneStatus_CONNECTION_STATE_CONNECTING       ControlPlaneStatus_ConnectionState = 2
	ControlPlaneStatus_CONNECTION_STATE_DISCONNECTED     ControlPlaneStatus_ConnectionState = 3
	ControlPlaneStatus_CONNECTION_STATE_WAITING_FOR_OTLP ControlPlaneStatus_ConnectionState = 4 // 等待 OTLP 恢复
)

// Enum value maps for ControlPlaneStatus_ConnectionState.
var (
	ControlPlaneStatus_ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_CONNECTED",
		2: "CONNECTION_STATE_CONNECTING",
		3: "CONNECTION_STATE_DISCONNECTED",
		4: "CONNECTION_STATE_WAITING_FOR_OTLP",
	}
	ControlPlaneStatus_ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED":      0,
		"CONNECTION_STATE_CONNECTED":        1,
		"CONNECTION_STATE_CONNECTING":       2,
		"CONNECTION_STATE_DISCONNECTED":     3,
		"CONNECTION_STATE_WAITING_FOR_OTLP": 4,
	}
)

func (x ControlPlaneStatus_ConnectionState) Enum() *ControlPlaneStatus_ConnectionState {
	p := new(ControlPlaneStatus_ConnectionState)
	*p = x
	return p
}

func (x ControlPlaneStatus_ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlPlaneStatus_ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_status_proto_enumTypes[2].Descriptor()
}

func (ControlPlaneStatus_ConnectionState) Type() protoreflect.EnumType {
	return &file_controlplane_v1_status_proto_enumTypes[2]
}

func (x ControlPlaneStatus_ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlPlaneStatus_ConnectionState.Descriptor instead.
func (ControlPlaneStatus_ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{4, 0}
}

// 状态上报请求
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent 身份标识
	AgentIdentity *AgentIdentity `protobuf:"bytes,1,opt,name=agent_identity,json=agentIdentity,proto3" json:"agent_identity,omitempty"`
	// Agent ID 字符串（与 DTO 兼容，优先使用此字段）
	AgentId string `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Agent 状态
	AgentStatus *AgentStatus `protobuf:"bytes,2,opt,name=agent_status,json=agentStatus,proto3" json:"agent_status,omitempty"`
	// JVM 指标
	JvmMetrics *JvmMetrics `protobuf:"bytes,3,opt,name=jvm_metrics,json=jvmMetrics,proto3" json:"jvm_metrics,omitempty"`
	// 任务执行结果
	TaskResults []*TaskResult `protobuf:"bytes,4,rep,name=task_results,json=taskResults,proto3" json:"task_results,omitempty"`
	// 配置确认
	ConfigAck *ConfigAcknowledgement `protobuf:"bytes,5,opt,name=config_ack,json=configAck,proto3" json:"config_ack,omitempty"`
	// 上报时间 (毫秒时间戳)
	TimestampMillis int64 `protobuf:"varint,6,opt,name=timestamp_millis,json=timestampMillis,proto3" json:"timestamp_millis,omitempty"`
	// 状态数据（JSON 字节数据，与 DTO 兼容）
	StatusData    []byte `protobuf:"bytes,8,opt,name=status_data,json=statusData,proto3" json:"status_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_controlplane_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetAgentIdentity() *AgentIdentity {
	if x != nil {
		return x.AgentIdentity
	}
	return nil
}

func (x *StatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusRequest) GetAgentStatus() *AgentStatus {
	if x != nil {
		return x.AgentStatus
	}
	return nil
}

func (x *StatusRequest) GetJvmMetrics() *JvmMetrics {
	if x != nil {
		return x.JvmMetrics
	}
	return nil
}

func (x *StatusRequest) GetTaskResults() []*TaskResult {
	if x != nil {
		return x.TaskResults
	}
	return nil
}

func (x *StatusRequest) GetConfigAck() *ConfigAcknowledgement {
	if x != nil {
		return x.ConfigAck
	}
	return nil
}

func (x *StatusRequest) GetTimestampMillis() int64 {
	if x != nil {
		return x.TimestampMillis
	}
	return 0
}

func (x *StatusRequest) GetStatusData() []byte {
	if x != nil {
		return x.StatusData
	}
	return nil
}

// 状态上报响应
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 服务端时间 (毫秒时间戳)
	ServerTimeMillis int64 `protobuf:"varint,2,opt,name=server_time_millis,json=serverTimeMillis,proto3" json:"server_time_millis,omitempty"`
	// 下次上报建议间隔 (毫秒)
	SuggestedReportIntervalMillis int64 `protobuf:"varint,3,opt,name=suggested_report_interval_millis,json=suggestedReportIntervalMillis,proto3" json:"suggested_report_interval_millis,omitempty"`
	// 已确认接收的任务结果 ID 列表
	AcknowledgedTaskIds []string `protobuf:"bytes,4,rep,name=acknowledged_task_ids,json=acknowledgedTaskIds,proto3" json:"acknowledged_task_ids,omitempty"`
	// 是否成功（与 DTO 兼容）
	Success bool `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（与 DTO 兼容）
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_controlplane_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusResponse) GetServerTimeMillis() int64 {
	if x != nil {
		return x.ServerTimeMillis
	}
	return 0
}

func (x *StatusResponse) GetSuggestedReportIntervalMillis() int64 {
	if x != nil {
		return x.SuggestedReportIntervalMillis
	}
	return 0
}

func (x *StatusResponse) GetAcknowledgedTaskIds() []string {
	if x != nil {
		return x.AcknowledgedTaskIds
	}
	return nil
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Agent 状态
type AgentStatus struct {
	state protoimpl.MessageState   `protogen:"open.v1"`
	State AgentStatus_RunningState `protobuf:"varint,1,opt,name=state,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.AgentStatus_RunningState" json:"state,omitempty"`
	// OTLP 导出状态
	OtlpStatus *OtlpExportStatus `protobuf:"bytes,2,opt,name=otlp_status,json=otlpStatus,proto3" json:"otlp_status,omitempty"`
	// 控制平面连接状态
	ControlPlaneStatus *ControlPlaneStatus `protobuf:"bytes,3,opt,name=control_plane_status,json=controlPlaneStatus,proto3" json:"control_plane_status,omitempty"`
	// 当前配置版本
	CurrentConfigVersion string `protobuf:"bytes,4,opt,name=current_config_version,json=currentConfigVersion,proto3" json:"current_config_version,omitempty"`
	// Agent 运行时长 (毫秒)
	UptimeMillis  int64 `protobuf:"varint,5,opt,name=uptime_millis,json=uptimeMillis,proto3" json:"uptime_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_controlplane_v1_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{2}
}

func (x *AgentStatus) GetState() AgentStatus_RunningState {
	if x != nil {
		return x.State
	}
	return AgentStatus_RUNNING_STATE_UNSPECIFIED
}

func (x *AgentStatus) GetOtlpStatus() *OtlpExportStatus {
	if x != nil {
		return x.OtlpStatus
	}
	return nil
}

func (x *AgentStatus) GetControlPlaneStatus() *ControlPlaneStatus {
	if x != nil {
		return x.ControlPlaneStatus
	}
	return nil
}

func (x *AgentStatus) GetCurrentConfigVersion() string {
	if x != nil {
		return x.CurrentConfigVersion
	}
	return ""
}

func (x *AgentStatus) GetUptimeMillis() int64 {
	if x != nil {
		return x.UptimeMillis
	}
	return 0
}

// OTLP 导出状态
type OtlpExportStatus struct {
	state protoimpl.MessageState       `protogen:"open.v1"`
	State OtlpExportStatus_HealthState `protobuf:"varint,1,opt,name=state,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatus_HealthState" json:"state,omitempty"`
	// 最后一次成功导出时间 (毫秒时间戳)
	LastSuccessTimeMillis int64 `protobuf:"varint,2,opt,name=last_success_time_millis,json=lastSuccessTimeMillis,proto3" json:"last_success_time_millis,omitempty"`
	// 最后一次失败时间 (毫秒时间戳)
	LastFailureTimeMillis int64 `protobuf:"varint,3,opt,name=last_failure_time_millis,json=lastFailureTimeMillis,proto3" json:"last_failure_time_millis,omitempty"`
	// 成功导出计数
	SuccessCount int64 `protobuf:"varint,4,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// 失败导出计数
	FailureCount int64 `protobuf:"varint,5,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	// 最后错误信息
	LastErrorMessage string `protobuf:"bytes,6,opt,name=last_error_message,json=lastErrorMessage,proto3" json:"last_error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OtlpExportStatus) Reset() {
	*x = OtlpExportStatus{}
	mi := &file_controlplane_v1_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtlpExportStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtlpExportStatus) ProtoMessage() {}

func (x *OtlpExportStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtlpExportStatus.ProtoReflect.Descriptor instead.
func (*OtlpExportStatus) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{3}
}

func (x *OtlpExportStatus) GetState() OtlpExportStatus_HealthState {
	if x != nil {
		return x.State
	}
	return OtlpExportStatus_HEALTH_STATE_UNSPECIFIED
}

func (x *OtlpExportStatus) GetLastSuccessTimeMillis() int64 {
	if x != nil {
		return x.LastSuccessTimeMillis
	}
	return 0
}

func (x *OtlpExportStatus) GetLastFailureTimeMillis() int64 {
	if x != nil {
		return x.LastFailureTimeMillis
	}
	return 0
}

func (x *OtlpExportStatus) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *OtlpExportStatus) GetFailureCount() int64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *OtlpExportStatus) GetLastErrorMessage() string {
	if x != nil {
		return x.LastErrorMessage
	}
	return ""
}

// 控制平面连接状态
type ControlPlaneStatus struct {
	state protoimpl.MessageState             `protogen:"open.v1"`
	State ControlPlaneStatus_ConnectionState `protobuf:"varint,1,opt,name=state,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatus_ConnectionState" json:"state,omitempty"`
	// 最后一次连接时间 (毫秒时间戳)
	LastConnectedTimeMillis int64 `protobuf:"varint,2,opt,name=last_connected_time_millis,json=lastConnectedTimeMillis,proto3" json:"last_connected_time_millis,omitempty"`
	// 重连次数
	ReconnectCount int32 `protobuf:"varint,3,opt,name=reconnect_count,json=reconnectCount,proto3" json:"reconnect_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlPlaneStatus) Reset() {
	*x = ControlPlaneStatus{}
	mi := &file_controlplane_v1_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneStatus) ProtoMessage() {}

func (x *ControlPlaneStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneStatus.ProtoReflect.Descriptor instead.
func (*ControlPlaneStatus) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{4}
}

func (x *ControlPlaneStatus) GetState() ControlPlaneStatus_ConnectionState {
	if x != nil {
		return x.State
	}
	return ControlPlaneStatus_CONNECTION_STATE_UNSPECIFIED
}

func (x *ControlPlaneStatus) GetLastConnectedTimeMillis() int64 {
	if x != nil {
		return x.LastConnectedTimeMillis
	}
	return 0
}

func (x *ControlPlaneStatus) GetReconnectCount() int32 {
	if x != nil {
		return x.ReconnectCount
	}
	return 0
}

// JVM 指标
type JvmMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 堆内存使用 (字节)
	HeapMemoryUsed int64 `protobuf:"varint,1,opt,name=heap_memory_used,json=heapMemoryUsed,proto3" json:"heap_memory_used,omitempty"`
	// 堆内存最大 (字节)
	HeapMemoryMax int64 `protobuf:"varint,2,opt,name=heap_memory_max,json=heapMemoryMax,proto3" json:"heap_memory_max,omitempty"`
	// 非堆内存使用 (字节)
	NonHeapMemoryUsed int64 `protobuf:"varint,3,opt,name=non_heap_memory_used,json=nonHeapMemoryUsed,proto3" json:"non_heap_memory_used,omitempty"`
	// 线程数
	ThreadCount int32 `protobuf:"varint,4,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	// 守护线程数
	DaemonThreadCount int32 `protobuf:"varint,5,opt,name=daemon_thread_count,json=daemonThreadCount,proto3" json:"daemon_thread_count,omitempty"`
	// GC 次数
	GcCount int64 `protobuf:"varint,6,opt,name=gc_count,json=gcCount,proto3" json:"gc_count,omitempty"`
	// GC 耗时 (毫秒)
	GcTimeMillis int64 `protobuf:"varint,7,opt,name=gc_time_millis,json=gcTimeMillis,proto3" json:"gc_time_millis,omitempty"`
	// CPU 使用率 (0.0 ~ 1.0)
	CpuUsage float64 `protobuf:"fixed64,8,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// 系统负载
	SystemLoadAverage float64 `protobuf:"fixed64,9,opt,name=system_load_average,json=systemLoadAverage,proto3" json:"system_load_average,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JvmMetrics) Reset() {
	*x = JvmMetrics{}
	mi := &file_controlplane_v1_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JvmMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JvmMetrics) ProtoMessage() {}

func (x *JvmMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JvmMetrics.ProtoReflect.Descriptor instead.
func (*JvmMetrics) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_status_proto_rawDescGZIP(), []int{5}
}

func (x *JvmMetrics) GetHeapMemoryUsed() int64 {
	if x != nil {
		return x.HeapMemoryUsed
	}
	return 0
}

func (x *JvmMetrics) GetHeapMemoryMax() int64 {
	if x != nil {
		return x.HeapMemoryMax
	}
	return 0
}

func (x *JvmMetrics) GetNonHeapMemoryUsed() int64 {
	if x != nil {
		return x.NonHeapMemoryUsed
	}
	return 0
}

func (x *JvmMetrics) GetThreadCount() int32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *JvmMetrics) GetDaemonThreadCount() int32 {
	if x != nil {
		return x.DaemonThreadCount
	}
	return 0
}

func (x *JvmMetrics) GetGcCount() int64 {
	if x != nil {
		return x.GcCount
	}
	return 0
}

func (x *JvmMetrics) GetGcTimeMillis() int64 {
	if x != nil {
		return x.GcTimeMillis
	}
	return 0
}

func (x *JvmMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *JvmMetrics) GetSystemLoadAverage() float64 {
	if x != nil {
		return x.SystemLoadAverage
	}
	return 0
}

var File_controlplane_v1_status_proto protoreflect.FileDescriptor

const file_controlplane_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x1ccontrolplane/v1/status.proto\x120io.opentelemetry.extension.controlplane.proto.v1\x1a\x1ccontrolplane/v1/common.proto\x1a\x1ccontrolplane/v1/config.proto\x1a\x1acontrolplane/v1/task.proto\"\xe8\x04\n" +
	"\rStatusRequest\x12f\n" +
	"\x0eagent_identity\x18\x01 \x01(\v2?.io.opentelemetry.extension.controlplane.proto.v1.AgentIdentityR\ragentIdentity\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12`\n" +
	"\fagent_status\x18\x02 \x01(\v2=.io.opentelemetry.extension.controlplane.proto.v1.AgentStatusR\vagentStatus\x12]\n" +
	"\vjvm_metrics\x18\x03 \x01(\v2<.io.opentelemetry.extension.controlplane.proto.v1.JvmMetricsR\n" +
	"jvmMetrics\x12_\n" +
	"\ftask_results\x18\x04 \x03(\v2<.io.opentelemetry.extension.controlplane.proto.v1.TaskResultR\vtaskResults\x12f\n" +
	"\n" +
	"config_ack\x18\x05 \x01(\v2G.io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgementR\tconfigAck\x12)\n" +
	"\x10timestamp_millis\x18\x06 \x01(\x03R\x0ftimestampMillis\x12\x1f\n" +
	"\vstatus_data\x18\b \x01(\fR\n" +
	"statusData\"\xd4\x02\n" +
	"\x0eStatusResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12,\n" +
	"\x12server_time_millis\x18\x02 \x01(\x03R\x10serverTimeMillis\x12G\n" +
	" suggested_report_interval_millis\x18\x03 \x01(\x03R\x1dsuggestedReportIntervalMillis\x122\n" +
	"\x15acknowledged_task_ids\x18\x04 \x03(\tR\x13acknowledgedTaskIds\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xc5\x04\n" +
	"\vAgentStatus\x12`\n" +
	"\x05state\x18\x01 \x01(\x0e2J.io.opentelemetry.extension.controlplane.proto.v1.AgentStatus.RunningStateR\x05state\x12c\n" +
	"\votlp_status\x18\x02 \x01(\v2B.io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatusR\n" +
	"otlpStatus\x12v\n" +
	"\x14control_plane_status\x18\x03 \x01(\v2D.io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatusR\x12controlPlaneStatus\x124\n" +
	"\x16current_config_version\x18\x04 \x01(\tR\x14currentConfigVersion\x12#\n" +
	"\ruptime_millis\x18\x05 \x01(\x03R\fuptimeMillis\"\x9b\x01\n" +
	"\fRunningState\x12\x1d\n" +
	"\x19RUNNING_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RUNNING_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15RUNNING_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16RUNNING_STATE_STOPPING\x10\x03\x12\x19\n" +
	"\x15RUNNING_STATE_STOPPED\x10\x04\"\xfb\x03\n" +
	"\x10OtlpExportStatus\x12d\n" +
	"\x05state\x18\x01 \x01(\x0e2N.io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatus.HealthStateR\x05state\x127\n" +
	"\x18last_success_time_millis\x18\x02 \x01(\x03R\x15lastSuccessTimeMillis\x127\n" +
	"\x18last_failure_time_millis\x18\x03 \x01(\x03R\x15lastFailureTimeMillis\x12#\n" +
	"\rsuccess_count\x18\x04 \x01(\x03R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x05 \x01(\x03R\ffailureCount\x12,\n" +
	"\x12last_error_message\x18\x06 \x01(\tR\x10lastErrorMessage\"\x96\x01\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HEALTH_STATE_UNKNOWN\x10\x01\x12\x18\n" +
	"\x14HEALTH_STATE_HEALTHY\x10\x02\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x03\x12\x1a\n" +
	"\x16HEALTH_STATE_UNHEALTHY\x10\x04\"\xa7\x03\n" +
	"\x12ControlPlaneStatus\x12j\n" +
	"\x05state\x18\x01 \x01(\x0e2T.io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatus.ConnectionStateR\x05state\x12;\n" +
	"\x1alast_connected_time_millis\x18\x02 \x01(\x03R\x17lastConnectedTimeMillis\x12'\n" +
	"\x0freconnect_count\x18\x03 \x01(\x05R\x0ereconnectCount\"\xbe\x01\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONNECTION_STATE_CONNECTED\x10\x01\x12\x1f\n" +
	"\x1bCONNECTION_STATE_CONNECTING\x10\x02\x12!\n" +
	"\x1dCONNECTION_STATE_DISCONNECTED\x10\x03\x12%\n" +
	"!CONNECTION_STATE_WAITING_FOR_OTLP\x10\x04\"\xf0\x02\n" +
	"\n" +
	"JvmMetrics\x12(\n" +
	"\x10heap_memory_used\x18\x01 \x01(\x03R\x0eheapMemoryUsed\x12&\n" +
	"\x0fheap_memory_max\x18\x02 \x01(\x03R\rheapMemoryMax\x12/\n" +
	"\x14non_heap_memory_used\x18\x03 \x01(\x03R\x11nonHeapMemoryUsed\x12!\n" +
	"\fthread_count\x18\x04 \x01(\x05R\vthreadCount\x12.\n" +
	"\x13daemon_thread_count\x18\x05 \x01(\x05R\x11daemonThreadCount\x12\x19\n" +
	"\bgc_count\x18\x06 \x01(\x03R\agcCount\x12$\n" +
	"\x0egc_time_millis\x18\a \x01(\x03R\fgcTimeMillis\x12\x1b\n" +
	"\tcpu_usage\x18\b \x01(\x01R\bcpuUsage\x12.\n" +
	"\x13system_load_average\x18\t \x01(\x01R\x11systemLoadAverageB\x8f\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\fStatusProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_status_proto_rawDescOnce sync.Once
	file_controlplane_v1_status_proto_rawDescData []byte
)

func file_controlplane_v1_status_proto_rawDescGZIP() []byte {
	file_controlplane_v1_status_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_status_proto_rawDesc), len(file_controlplane_v1_status_proto_rawDesc)))
	})
	return file_controlplane_v1_status_proto_rawDescData
}

var file_controlplane_v1_status_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_controlplane_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_controlplane_v1_status_proto_goTypes = []any{
	(AgentStatus_RunningState)(0),           // 0: io.opentelemetry.extension.controlplane.proto.v1.AgentStatus.RunningState
	(OtlpExportStatus_HealthState)(0),       // 1: io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatus.HealthState
	(ControlPlaneStatus_ConnectionState)(0), // 2: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatus.ConnectionState
	(*StatusRequest)(nil),                   // 3: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest
	(*StatusResponse)(nil),                  // 4: io.opentelemetry.extension.controlplane.proto.v1.StatusResponse
	(*AgentStatus)(nil),                     // 5: io.opentelemetry.extension.controlplane.proto.v1.AgentStatus
	(*OtlpExportStatus)(nil),                // 6: io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatus
	(*ControlPlaneStatus)(nil),              // 7: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatus
	(*JvmMetrics)(nil),                      // 8: io.opentelemetry.extension.controlplane.proto.v1.JvmMetrics
	(*AgentIdentity)(nil),                   // 9: io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	(*TaskResult)(nil),                      // 10: io.opentelemetry.extension.controlplane.proto.v1.TaskResult
	(*ConfigAcknowledgement)(nil),           // 11: io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement
	(*ResponseStatus)(nil),                  // 12: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
}
var file_controlplane_v1_status_proto_depIdxs = []int32{
	9,  // 0: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest.agent_identity:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentIdentity
	5,  // 1: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest.agent_status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentStatus
	8,  // 2: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest.jvm_metrics:type_name -> io.opentelemetry.extension.controlplane.proto.v1.JvmMetrics
	10, // 3: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest.task_results:type_name -> io.opentelemetry.extension.controlplane.proto.v1.TaskResult
	11, // 4: io.opentelemetry.extension.controlplane.proto.v1.StatusRequest.config_ack:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ConfigAcknowledgement
	12, // 5: io.opentelemetry.extension.controlplane.proto.v1.StatusResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	0,  // 6: io.opentelemetry.extension.controlplane.proto.v1.AgentStatus.state:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentStatus.RunningState
	6,  // 7: io.opentelemetry.extension.controlplane.proto.v1.AgentStatus.otlp_status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatus
	7,  // 8: io.opentelemetry.extension.controlplane.proto.v1.AgentStatus.control_plane_status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatus
	1,  // 9: io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatus.state:type_name -> io.opentelemetry.extension.controlplane.proto.v1.OtlpExportStatus.HealthState
	2,  // 10: io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatus.state:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ControlPlaneStatus.ConnectionState
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_controlplane_v1_status_proto_init() }
func file_controlplane_v1_status_proto_init() {
	if File_controlplane_v1_status_proto != nil {
		return
	}
	file_controlplane_v1_common_proto_init()
	file_controlplane_v1_config_proto_init()
	file_controlplane_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_status_proto_rawDesc), len(file_controlplane_v1_status_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_status_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_status_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_status_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_status_proto_msgTypes,
	}.Build()
	File_controlplane_v1_status_proto = out.File
	file_controlplane_v1_status_proto_goTypes = nil
	file_controlplane_v1_status_proto_depIdxs = nil
}
