//
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: controlplane/v1/task.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分片上传状态
type ChunkUploadStatus int32

const (
	ChunkUploadStatus_CHUNK_UPLOAD_STATUS_UNSPECIFIED       ChunkUploadStatus = 0
	ChunkUploadStatus_CHUNK_UPLOAD_STATUS_CHUNK_RECEIVED    ChunkUploadStatus = 1 // 分片已接收
	ChunkUploadStatus_CHUNK_UPLOAD_STATUS_UPLOAD_COMPLETE   ChunkUploadStatus = 2 // 上传完成
	ChunkUploadStatus_CHUNK_UPLOAD_STATUS_CHECKSUM_MISMATCH ChunkUploadStatus = 3 // 校验失败
	ChunkUploadStatus_CHUNK_UPLOAD_STATUS_UPLOAD_FAILED     ChunkUploadStatus = 4 // 上传失败
)

// Enum value maps for ChunkUploadStatus.
var (
	ChunkUploadStatus_name = map[int32]string{
		0: "CHUNK_UPLOAD_STATUS_UNSPECIFIED",
		1: "CHUNK_UPLOAD_STATUS_CHUNK_RECEIVED",
		2: "CHUNK_UPLOAD_STATUS_UPLOAD_COMPLETE",
		3: "CHUNK_UPLOAD_STATUS_CHECKSUM_MISMATCH",
		4: "CHUNK_UPLOAD_STATUS_UPLOAD_FAILED",
	}
	ChunkUploadStatus_value = map[string]int32{
		"CHUNK_UPLOAD_STATUS_UNSPECIFIED":       0,
		"CHUNK_UPLOAD_STATUS_CHUNK_RECEIVED":    1,
		"CHUNK_UPLOAD_STATUS_UPLOAD_COMPLETE":   2,
		"CHUNK_UPLOAD_STATUS_CHECKSUM_MISMATCH": 3,
		"CHUNK_UPLOAD_STATUS_UPLOAD_FAILED":     4,
	}
)

func (x ChunkUploadStatus) Enum() *ChunkUploadStatus {
	p := new(ChunkUploadStatus)
	*p = x
	return p
}

func (x ChunkUploadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkUploadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_task_proto_enumTypes[0].Descriptor()
}

func (ChunkUploadStatus) Type() protoreflect.EnumType {
	return &file_controlplane_v1_task_proto_enumTypes[0]
}

func (x ChunkUploadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkUploadStatus.Descriptor instead.
func (ChunkUploadStatus) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{0}
}

// 任务类型（枚举）
type Task_TaskType int32

const (
	Task_TASK_TYPE_UNSPECIFIED       Task_TaskType = 0
	Task_TASK_TYPE_THREAD_DUMP       Task_TaskType = 1   // 线程转储
	Task_TASK_TYPE_HEAP_DUMP         Task_TaskType = 2   // 堆转储
	Task_TASK_TYPE_GC_INFO           Task_TaskType = 3   // GC 信息
	Task_TASK_TYPE_SYSTEM_PROPERTIES Task_TaskType = 4   // 系统属性
	Task_TASK_TYPE_ENV_VARIABLES     Task_TaskType = 5   // 环境变量
	Task_TASK_TYPE_CUSTOM            Task_TaskType = 100 // 自定义任务
)

// Enum value maps for Task_TaskType.
var (
	Task_TaskType_name = map[int32]string{
		0:   "TASK_TYPE_UNSPECIFIED",
		1:   "TASK_TYPE_THREAD_DUMP",
		2:   "TASK_TYPE_HEAP_DUMP",
		3:   "TASK_TYPE_GC_INFO",
		4:   "TASK_TYPE_SYSTEM_PROPERTIES",
		5:   "TASK_TYPE_ENV_VARIABLES",
		100: "TASK_TYPE_CUSTOM",
	}
	Task_TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED":       0,
		"TASK_TYPE_THREAD_DUMP":       1,
		"TASK_TYPE_HEAP_DUMP":         2,
		"TASK_TYPE_GC_INFO":           3,
		"TASK_TYPE_SYSTEM_PROPERTIES": 4,
		"TASK_TYPE_ENV_VARIABLES":     5,
		"TASK_TYPE_CUSTOM":            100,
	}
)

func (x Task_TaskType) Enum() *Task_TaskType {
	p := new(Task_TaskType)
	*p = x
	return p
}

func (x Task_TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_task_proto_enumTypes[1].Descriptor()
}

func (Task_TaskType) Type() protoreflect.EnumType {
	return &file_controlplane_v1_task_proto_enumTypes[1]
}

func (x Task_TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_TaskType.Descriptor instead.
func (Task_TaskType) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{3, 0}
}

// 任务优先级（枚举）
type Task_Priority int32

const (
	Task_PRIORITY_UNSPECIFIED Task_Priority = 0
	Task_PRIORITY_LOW         Task_Priority = 1
	Task_PRIORITY_NORMAL      Task_Priority = 2
	Task_PRIORITY_HIGH        Task_Priority = 3
)

// Enum value maps for Task_Priority.
var (
	Task_Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
	}
	Task_Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
	}
)

func (x Task_Priority) Enum() *Task_Priority {
	p := new(Task_Priority)
	*p = x
	return p
}

func (x Task_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_task_proto_enumTypes[2].Descriptor()
}

func (Task_Priority) Type() protoreflect.EnumType {
	return &file_controlplane_v1_task_proto_enumTypes[2]
}

func (x Task_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_Priority.Descriptor instead.
func (Task_Priority) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{3, 1}
}

// 任务拉取请求
type TaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID 字符串（用于鉴权和路由）
	AgentId string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 长轮询超时时间 (毫秒)
	LongPollTimeoutMillis int64 `protobuf:"varint,2,opt,name=long_poll_timeout_millis,json=longPollTimeoutMillis,proto3" json:"long_poll_timeout_millis,omitempty"`
	// Agent 当前能力
	Capabilities  *AgentCapabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_controlplane_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskRequest) GetLongPollTimeoutMillis() int64 {
	if x != nil {
		return x.LongPollTimeoutMillis
	}
	return 0
}

func (x *TaskRequest) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Agent 能力
type AgentCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 支持的任务类型
	SupportedTaskTypes []string `protobuf:"bytes,1,rep,name=supported_task_types,json=supportedTaskTypes,proto3" json:"supported_task_types,omitempty"`
	// 最大并发任务数
	MaxConcurrentTasks int32 `protobuf:"varint,2,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	// 最大结果大小 (字节)
	MaxResultSizeBytes int64 `protobuf:"varint,3,opt,name=max_result_size_bytes,json=maxResultSizeBytes,proto3" json:"max_result_size_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_controlplane_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *AgentCapabilities) GetSupportedTaskTypes() []string {
	if x != nil {
		return x.SupportedTaskTypes
	}
	return nil
}

func (x *AgentCapabilities) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *AgentCapabilities) GetMaxResultSizeBytes() int64 {
	if x != nil {
		return x.MaxResultSizeBytes
	}
	return 0
}

// 任务拉取响应
type TaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态
	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 下发的任务列表
	Tasks []*Task `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// 下次轮询建议间隔 (毫秒)
	SuggestedPollIntervalMillis int64 `protobuf:"varint,3,opt,name=suggested_poll_interval_millis,json=suggestedPollIntervalMillis,proto3" json:"suggested_poll_interval_millis,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_controlplane_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TaskResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskResponse) GetSuggestedPollIntervalMillis() int64 {
	if x != nil {
		return x.SuggestedPollIntervalMillis
	}
	return 0
}

// 任务定义
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务 ID
	TaskId string        `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type   Task_TaskType `protobuf:"varint,2,opt,name=type,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.Task_TaskType" json:"type,omitempty"`
	// 任务类型字符串（与 DTO 兼容，优先使用此字段）
	TaskTypeName string `protobuf:"bytes,12,opt,name=task_type_name,json=taskTypeName,proto3" json:"task_type_name,omitempty"`
	// 任务参数 (JSON 格式)
	ParametersJson string        `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	Priority       Task_Priority `protobuf:"varint,4,opt,name=priority,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.Task_Priority" json:"priority,omitempty"`
	// 任务优先级数值（与 DTO 兼容，0-100）
	PriorityNum int32 `protobuf:"varint,13,opt,name=priority_num,json=priorityNum,proto3" json:"priority_num,omitempty"`
	// 任务超时时间 (毫秒)
	TimeoutMillis int64 `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	// 任务创建时间 (毫秒时间戳)
	CreatedAtMillis int64 `protobuf:"varint,6,opt,name=created_at_millis,json=createdAtMillis,proto3" json:"created_at_millis,omitempty"`
	// 任务过期时间 (毫秒时间戳)
	ExpiresAtMillis int64 `protobuf:"varint,7,opt,name=expires_at_millis,json=expiresAtMillis,proto3" json:"expires_at_millis,omitempty"`
	// 最大可接受延迟 (毫秒)，超过此延迟的任务将被拒绝
	MaxAcceptableDelayMillis int64 `protobuf:"varint,14,opt,name=max_acceptable_delay_millis,json=maxAcceptableDelayMillis,proto3" json:"max_acceptable_delay_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_controlplane_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetType() Task_TaskType {
	if x != nil {
		return x.Type
	}
	return Task_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetTaskTypeName() string {
	if x != nil {
		return x.TaskTypeName
	}
	return ""
}

func (x *Task) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

func (x *Task) GetPriority() Task_Priority {
	if x != nil {
		return x.Priority
	}
	return Task_PRIORITY_UNSPECIFIED
}

func (x *Task) GetPriorityNum() int32 {
	if x != nil {
		return x.PriorityNum
	}
	return 0
}

func (x *Task) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *Task) GetCreatedAtMillis() int64 {
	if x != nil {
		return x.CreatedAtMillis
	}
	return 0
}

func (x *Task) GetExpiresAtMillis() int64 {
	if x != nil {
		return x.ExpiresAtMillis
	}
	return 0
}

func (x *Task) GetMaxAcceptableDelayMillis() int64 {
	if x != nil {
		return x.MaxAcceptableDelayMillis
	}
	return 0
}

// 任务结果（用于 status.proto 上报，使用全局 TaskStatus）
type TaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务 ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 执行状态（使用全局统一枚举）
	Status TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.TaskStatus" json:"status,omitempty"`
	// 任务开始时间 (毫秒时间戳)
	StartedAtMillis int64 `protobuf:"varint,3,opt,name=started_at_millis,json=startedAtMillis,proto3" json:"started_at_millis,omitempty"`
	// 任务完成时间 (毫秒时间戳)
	CompletedAtMillis int64 `protobuf:"varint,4,opt,name=completed_at_millis,json=completedAtMillis,proto3" json:"completed_at_millis,omitempty"`
	// 任务执行耗时 (毫秒)
	ExecutionTimeMillis int64 `protobuf:"varint,12,opt,name=execution_time_millis,json=executionTimeMillis,proto3" json:"execution_time_millis,omitempty"`
	// 结果数据（二进制）
	ResultData []byte `protobuf:"bytes,5,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	// 结果数据 JSON 格式
	ResultJson string `protobuf:"bytes,13,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// 结果数据类型 (MIME type)
	ResultDataType string `protobuf:"bytes,6,opt,name=result_data_type,json=resultDataType,proto3" json:"result_data_type,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,14,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 错误信息
	ErrorMessage string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 重试次数
	RetryCount int32 `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	// 压缩类型（使用全局统一枚举）
	Compression CompressionType `protobuf:"varint,9,opt,name=compression,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.CompressionType" json:"compression,omitempty"`
	// 原始大小 (字节)
	OriginalSize int64 `protobuf:"varint,10,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	// 压缩后大小 (字节)
	CompressedSize int64 `protobuf:"varint,11,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_controlplane_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetStartedAtMillis() int64 {
	if x != nil {
		return x.StartedAtMillis
	}
	return 0
}

func (x *TaskResult) GetCompletedAtMillis() int64 {
	if x != nil {
		return x.CompletedAtMillis
	}
	return 0
}

func (x *TaskResult) GetExecutionTimeMillis() int64 {
	if x != nil {
		return x.ExecutionTimeMillis
	}
	return 0
}

func (x *TaskResult) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *TaskResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *TaskResult) GetResultDataType() string {
	if x != nil {
		return x.ResultDataType
	}
	return ""
}

func (x *TaskResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskResult) GetCompression() CompressionType {
	if x != nil {
		return x.Compression
	}
	return CompressionType_COMPRESSION_TYPE_NONE
}

func (x *TaskResult) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *TaskResult) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

// 分片任务结果 (用于大结果上传)
type ChunkedTaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务 ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 分片上传会话 ID
	UploadId string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// 分片索引 (从 0 开始)
	ChunkIndex int32 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// 总分片数
	TotalChunks int32 `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	// 分片数据
	ChunkData []byte `protobuf:"bytes,5,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	// 分片校验和 (MD5)
	ChunkChecksum string `protobuf:"bytes,6,opt,name=chunk_checksum,json=chunkChecksum,proto3" json:"chunk_checksum,omitempty"`
	// 是否最后一片
	IsLastChunk bool `protobuf:"varint,7,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	// 原始文件名 (如 "taskid.collapsed")，仅第一片需要填写
	FileName string `protobuf:"bytes,8,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// 内容类型提示 (如 "application/octet-stream")
	ContentType   string `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkedTaskResult) Reset() {
	*x = ChunkedTaskResult{}
	mi := &file_controlplane_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkedTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkedTaskResult) ProtoMessage() {}

func (x *ChunkedTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkedTaskResult.ProtoReflect.Descriptor instead.
func (*ChunkedTaskResult) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *ChunkedTaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ChunkedTaskResult) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ChunkedTaskResult) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkedTaskResult) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ChunkedTaskResult) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *ChunkedTaskResult) GetChunkChecksum() string {
	if x != nil {
		return x.ChunkChecksum
	}
	return ""
}

func (x *ChunkedTaskResult) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *ChunkedTaskResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ChunkedTaskResult) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// 分片上传响应
type ChunkedUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 上传会话 ID
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// 已接收的分片索引
	ReceivedChunkIndex int32 `protobuf:"varint,2,opt,name=received_chunk_index,json=receivedChunkIndex,proto3" json:"received_chunk_index,omitempty"`
	// 状态（使用全局枚举）
	Status ChunkUploadStatus `protobuf:"varint,3,opt,name=status,proto3,enum=io.opentelemetry.extension.controlplane.proto.v1.ChunkUploadStatus" json:"status,omitempty"`
	// 错误信息
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkedUploadResponse) Reset() {
	*x = ChunkedUploadResponse{}
	mi := &file_controlplane_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkedUploadResponse) ProtoMessage() {}

func (x *ChunkedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkedUploadResponse.ProtoReflect.Descriptor instead.
func (*ChunkedUploadResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkedUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ChunkedUploadResponse) GetReceivedChunkIndex() int32 {
	if x != nil {
		return x.ReceivedChunkIndex
	}
	return 0
}

func (x *ChunkedUploadResponse) GetStatus() ChunkUploadStatus {
	if x != nil {
		return x.Status
	}
	return ChunkUploadStatus_CHUNK_UPLOAD_STATUS_UNSPECIFIED
}

func (x *ChunkedUploadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_controlplane_v1_task_proto protoreflect.FileDescriptor

const file_controlplane_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x1acontrolplane/v1/task.proto\x120io.opentelemetry.extension.controlplane.proto.v1\x1a\x1ccontrolplane/v1/common.proto\"\xe0\x01\n" +
	"\vTaskRequest\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x127\n" +
	"\x18long_poll_timeout_millis\x18\x02 \x01(\x03R\x15longPollTimeoutMillis\x12g\n" +
	"\fcapabilities\x18\x03 \x01(\v2C.io.opentelemetry.extension.controlplane.proto.v1.AgentCapabilitiesR\fcapabilitiesJ\x04\b\x01\x10\x02R\x0eagent_identity\"\xaa\x01\n" +
	"\x11AgentCapabilities\x120\n" +
	"\x14supported_task_types\x18\x01 \x03(\tR\x12supportedTaskTypes\x120\n" +
	"\x14max_concurrent_tasks\x18\x02 \x01(\x05R\x12maxConcurrentTasks\x121\n" +
	"\x15max_result_size_bytes\x18\x03 \x01(\x03R\x12maxResultSizeBytes\"\x9f\x02\n" +
	"\fTaskResponse\x12X\n" +
	"\x06status\x18\x01 \x01(\v2@.io.opentelemetry.extension.controlplane.proto.v1.ResponseStatusR\x06status\x12L\n" +
	"\x05tasks\x18\x02 \x03(\v26.io.opentelemetry.extension.controlplane.proto.v1.TaskR\x05tasks\x12C\n" +
	"\x1esuggested_poll_interval_millis\x18\x03 \x01(\x03R\x1bsuggestedPollIntervalMillisJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\asuccessR\rerror_message\"\xa8\x06\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12S\n" +
	"\x04type\x18\x02 \x01(\x0e2?.io.opentelemetry.extension.controlplane.proto.v1.Task.TaskTypeR\x04type\x12$\n" +
	"\x0etask_type_name\x18\f \x01(\tR\ftaskTypeName\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\x12[\n" +
	"\bpriority\x18\x04 \x01(\x0e2?.io.opentelemetry.extension.controlplane.proto.v1.Task.PriorityR\bpriority\x12!\n" +
	"\fpriority_num\x18\r \x01(\x05R\vpriorityNum\x12%\n" +
	"\x0etimeout_millis\x18\x05 \x01(\x03R\rtimeoutMillis\x12*\n" +
	"\x11created_at_millis\x18\x06 \x01(\x03R\x0fcreatedAtMillis\x12*\n" +
	"\x11expires_at_millis\x18\a \x01(\x03R\x0fexpiresAtMillis\x12=\n" +
	"\x1bmax_acceptable_delay_millis\x18\x0e \x01(\x03R\x18maxAcceptableDelayMillis\"\xc4\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TASK_TYPE_THREAD_DUMP\x10\x01\x12\x17\n" +
	"\x13TASK_TYPE_HEAP_DUMP\x10\x02\x12\x15\n" +
	"\x11TASK_TYPE_GC_INFO\x10\x03\x12\x1f\n" +
	"\x1bTASK_TYPE_SYSTEM_PROPERTIES\x10\x04\x12\x1b\n" +
	"\x17TASK_TYPE_ENV_VARIABLES\x10\x05\x12\x14\n" +
	"\x10TASK_TYPE_CUSTOM\x10d\"^\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\"\x8f\x05\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12T\n" +
	"\x06status\x18\x02 \x01(\x0e2<.io.opentelemetry.extension.controlplane.proto.v1.TaskStatusR\x06status\x12*\n" +
	"\x11started_at_millis\x18\x03 \x01(\x03R\x0fstartedAtMillis\x12.\n" +
	"\x13completed_at_millis\x18\x04 \x01(\x03R\x11completedAtMillis\x122\n" +
	"\x15execution_time_millis\x18\f \x01(\x03R\x13executionTimeMillis\x12\x1f\n" +
	"\vresult_data\x18\x05 \x01(\fR\n" +
	"resultData\x12\x1f\n" +
	"\vresult_json\x18\r \x01(\tR\n" +
	"resultJson\x12(\n" +
	"\x10result_data_type\x18\x06 \x01(\tR\x0eresultDataType\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0e \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12c\n" +
	"\vcompression\x18\t \x01(\x0e2A.io.opentelemetry.extension.controlplane.proto.v1.CompressionTypeR\vcompression\x12#\n" +
	"\roriginal_size\x18\n" +
	" \x01(\x03R\foriginalSize\x12'\n" +
	"\x0fcompressed_size\x18\v \x01(\x03R\x0ecompressedSize\"\xb7\x02\n" +
	"\x11ChunkedTaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x05 \x01(\fR\tchunkData\x12%\n" +
	"\x0echunk_checksum\x18\x06 \x01(\tR\rchunkChecksum\x12\"\n" +
	"\ris_last_chunk\x18\a \x01(\bR\visLastChunk\x12\x1b\n" +
	"\tfile_name\x18\b \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\"\xe8\x01\n" +
	"\x15ChunkedUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x120\n" +
	"\x14received_chunk_index\x18\x02 \x01(\x05R\x12receivedChunkIndex\x12[\n" +
	"\x06status\x18\x03 \x01(\x0e2C.io.opentelemetry.extension.controlplane.proto.v1.ChunkUploadStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*\xdb\x01\n" +
	"\x11ChunkUploadStatus\x12#\n" +
	"\x1fCHUNK_UPLOAD_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"CHUNK_UPLOAD_STATUS_CHUNK_RECEIVED\x10\x01\x12'\n" +
	"#CHUNK_UPLOAD_STATUS_UPLOAD_COMPLETE\x10\x02\x12)\n" +
	"%CHUNK_UPLOAD_STATUS_CHECKSUM_MISMATCH\x10\x03\x12%\n" +
	"!CHUNK_UPLOAD_STATUS_UPLOAD_FAILED\x10\x04B\x8d\x01\n" +
	"4io.opentelemetry.sdk.extension.controlplane.proto.v1B\n" +
	"TaskProtosZIgo.opentelemetry.io/collector/custom/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_task_proto_rawDescOnce sync.Once
	file_controlplane_v1_task_proto_rawDescData []byte
)

func file_controlplane_v1_task_proto_rawDescGZIP() []byte {
	file_controlplane_v1_task_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_task_proto_rawDesc), len(file_controlplane_v1_task_proto_rawDesc)))
	})
	return file_controlplane_v1_task_proto_rawDescData
}

var file_controlplane_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_controlplane_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_controlplane_v1_task_proto_goTypes = []any{
	(ChunkUploadStatus)(0),        // 0: io.opentelemetry.extension.controlplane.proto.v1.ChunkUploadStatus
	(Task_TaskType)(0),            // 1: io.opentelemetry.extension.controlplane.proto.v1.Task.TaskType
	(Task_Priority)(0),            // 2: io.opentelemetry.extension.controlplane.proto.v1.Task.Priority
	(*TaskRequest)(nil),           // 3: io.opentelemetry.extension.controlplane.proto.v1.TaskRequest
	(*AgentCapabilities)(nil),     // 4: io.opentelemetry.extension.controlplane.proto.v1.AgentCapabilities
	(*TaskResponse)(nil),          // 5: io.opentelemetry.extension.controlplane.proto.v1.TaskResponse
	(*Task)(nil),                  // 6: io.opentelemetry.extension.controlplane.proto.v1.Task
	(*TaskResult)(nil),            // 7: io.opentelemetry.extension.controlplane.proto.v1.TaskResult
	(*ChunkedTaskResult)(nil),     // 8: io.opentelemetry.extension.controlplane.proto.v1.ChunkedTaskResult
	(*ChunkedUploadResponse)(nil), // 9: io.opentelemetry.extension.controlplane.proto.v1.ChunkedUploadResponse
	(*ResponseStatus)(nil),        // 10: io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	(TaskStatus)(0),               // 11: io.opentelemetry.extension.controlplane.proto.v1.TaskStatus
	(CompressionType)(0),          // 12: io.opentelemetry.extension.controlplane.proto.v1.CompressionType
}
var file_controlplane_v1_task_proto_depIdxs = []int32{
	4,  // 0: io.opentelemetry.extension.controlplane.proto.v1.TaskRequest.capabilities:type_name -> io.opentelemetry.extension.controlplane.proto.v1.AgentCapabilities
	10, // 1: io.opentelemetry.extension.controlplane.proto.v1.TaskResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ResponseStatus
	6,  // 2: io.opentelemetry.extension.controlplane.proto.v1.TaskResponse.tasks:type_name -> io.opentelemetry.extension.controlplane.proto.v1.Task
	1,  // 3: io.opentelemetry.extension.controlplane.proto.v1.Task.type:type_name -> io.opentelemetry.extension.controlplane.proto.v1.Task.TaskType
	2,  // 4: io.opentelemetry.extension.controlplane.proto.v1.Task.priority:type_name -> io.opentelemetry.extension.controlplane.proto.v1.Task.Priority
	11, // 5: io.opentelemetry.extension.controlplane.proto.v1.TaskResult.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.TaskStatus
	12, // 6: io.opentelemetry.extension.controlplane.proto.v1.TaskResult.compression:type_name -> io.opentelemetry.extension.controlplane.proto.v1.CompressionType
	0,  // 7: io.opentelemetry.extension.controlplane.proto.v1.ChunkedUploadResponse.status:type_name -> io.opentelemetry.extension.controlplane.proto.v1.ChunkUploadStatus
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_controlplane_v1_task_proto_init() }
func file_controlplane_v1_task_proto_init() {
	if File_controlplane_v1_task_proto != nil {
		return
	}
	file_controlplane_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_task_proto_rawDesc), len(file_controlplane_v1_task_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_task_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_task_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_task_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_task_proto_msgTypes,
	}.Build()
	File_controlplane_v1_task_proto = out.File
	file_controlplane_v1_task_proto_goTypes = nil
	file_controlplane_v1_task_proto_depIdxs = nil
}
